export const metadata = {
  // fields
  id: {
    source: "field",
    dataType: "STR",
    label: "Unique Id",
    editable: false,
    show: true,
    clipboard: true,
  },
  name: {
    source: "field",
    dataType: "STR",
    label: "Name",
    editable: true,
    show: true,
  },
  shortName: {
    source: "field",
    dataType: "STR",
    label: "Short name",
    editable: true,
    show: true,
  },
  //related
  owner: {
    source: "related",
    dataType: "FKEY",
    label: "Owner",
    editable: true,
    show: true,
    labelField: "fullName",
    link: "username",
    model: "User",
  },
  parent: {
    source: "related",
    dataType: "FKEY",
    label: "Source",
    editable: true,
    show: true,
    placeholder: "No parent assigned.",
    labelField: "name",
    link: "id",
    model: "Type",
  },
  // attributes
  mk1Identifier: {
    source: "attribute",
    editable: false,
    show: false,
  },
  mk2Identifier: {
    source: "attribute",
    editable: false,
    show: false,
  },
  altIdentifier: {
    source: "attribute",
    editable: true,
    show: false,
  },
  language: {
    source: "attribute",
    placement: "infocard",
    editable: true,
    show: true,
    placeholder: "No language(s) assigned.",
  },
  date: {
    source: "attribute",
    placement: "infocard",
    editable: true,
    show: true,
    placeholder: "No date assigned.",
  },
  endDate: {
    source: "attribute",
    placement: "infocard",
    editable: true,
    show: true,
    placeholder: "No date assigned.",
  },
  startDate: {
    source: "attribute",
    placement: "infocard",
    editable: true,
    show: true,
    placeholder: "No date assigned.",
  },
  recordType: {
    source: "attribute",
    placement: "infocard",
    editable: true,
    show: true,
    placeholder: "No type assigned.",
  },
  debtPhrase: {
    source: "attribute",
    editable: true,
    show: false,
  },
  debtAmount: {
    source: "attribute",
    editable: true,
    show: false,
  },
  debtUnit: {
    source: "attribute",
    editable: true,
    show: false,
  },
  debtUnitSource: {
    source: "attribute",
    editable: true,
    show: false,
  },
  debtSource: {
    source: "attribute",
    editable: true,
    show: false,
  },
  locale: {
    source: "attribute",
    editable: true,
    show: true,
    placeholder: "No locale(s) assigned.",
  },
  hasInventory: {
    source: "attribute",
    editable: true,
    show: true,
  },
  description: {
    source: "attribute",
    editable: true,
    show: true,
    placeholder: "No description assigned.",
  },
};
