FROM python:3.7-buster
WORKDIR /app

ENV PYTHONUNBUFFERED 1 \
    PYTHONDONTWRITEBYTECODE 1 \
    LANG=en_US.UTF-8

# Install wait-for-it to wait for mysql database when testing locally
COPY docker/wait-for-it.sh /usr/local/bin/
RUN chmod u+x /usr/local/bin/wait-for-it.sh

RUN adduser --disabled-password --gecos "Whisky" --uid 1001 --gid 0 \
    --home /home/whisky whisky && \
    chmod 1777 /home/whisky

RUN rm -rf /var/lib/apt/lists/* && apt-get update
RUN apt-get install -y libxml2-dev xmlsec1 libxmlsec1-dev libxmlsec1-openssl --no-install-recommends

COPY requirements*.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-dev.txt

RUN mkdir -p /var/log/django && touch /var/log/django/dalme_app.log && \
    chmod 777 /var/log/django/dalme_app.log

COPY docker/dev/entrypoint.dev /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 8000 8443
CMD ["gunicorn", "-c", "/app/docker/gunicorn.conf.py", "dalme.wsgi"]
