FROM python:3.7-slim

ENV PYTHONUNBUFFERED 1 \
    PYTHONDONTWRITEBYTECODE 1 \
    LANG=en_US.UTF-8

RUN rm -rf /var/lib/apt/lists/* && apt-get update
RUN apt-get install -y libcurl4-openssl-dev libssl-dev libmariadbd-dev gcc xmlsec1 --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*

#RUN mkdir -p /opt/python/log/celery/ /opt/python/run/celery/ && \
#    addgroup celery && \
#    adduser --disabled-password --gecos "Celery" --ingroup celery --home /home/celery celery && \
#    chmod 1777 /home/celery && \
#    chown celery:celery /opt/python/log/celery/ && \
#    chown celery:celery /opt/python/run/celery/

RUN mkdir -p /opt/python/log/celery/ /opt/python/run/celery/

RUN mkdir -p /var/log/django && touch /var/log/django/dalme_app.log && \
    chmod 777 /var/log/django/dalme_app.log

# USER celery
# ENV PATH="/home/celery/.local/bin:${PATH}"
WORKDIR /app

COPY requirements*.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-dev.txt

#RUN pip install --upgrade pip && \
#    pip install --user --no-cache-dir -r requirements-dev.txt
