FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV LANG=en_US.UTF-8

RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libxmlsec1-openssl \
    vim \
    xmlsec1
RUN apt-get clean

WORKDIR /opt/app
COPY ./manage.py .
COPY ./requirements.txt .
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r ./requirements.txt

COPY dalme ./dalme
COPY dalme_api ./dalme_api
COPY dalme_app ./dalme_app
COPY dalme_public ./dalme_public
COPY dalme_purl ./dalme_purl
COPY templates ./templates
COPY static ./static
COPY ssl-certs ./ssl-certs

COPY ./config/beta/gunicorn.conf.py .
COPY ./config/beta/supervisord.conf /etc/supervisord.conf

RUN mkdir -p /var/log/supervisord /var/run/supervisord
RUN mkdir -p /var/log/djangoq /var/run/djangoq

RUN mkdir -p /var/log/django && \
    touch /var/log/django/dalme_app.log && \
    chmod 777 /var/log/django/dalme_app.log

STOPSIGNAL SIGINT
