# Generated by Django 5.1.4 on 2025-02-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.CharField(
                blank=True,
                help_text='Path to an image file containing a graphic logo to be used in this site, e.g. "images/logo.svg".',
                max_length=255,
            ),
        ),
    ]
