# Generated by Django 5.1.4 on 2025-04-05 19:54

import wagtail.fields

from django.db import migrations

import web.extensions.images.blocks.inline_image
import web.extensions.team.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_alter_settings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('document', 10),
                    ('heading', 13),
                    ('inline_image', 23),
                    ('page', 24),
                    ('pullquote', 25),
                    ('subsection', 51),
                    ('table', 41),
                    ('team_list', 56),
                    ('text', 57),
                ],
                block_lookup={
                    0: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [('document', 'Document'), ('publication', 'Publication'), ('talk', 'Talk')],
                            'help_text': 'Type of document.',
                        },
                    ),
                    1: ('wagtail.blocks.DecimalBlock', (), {'help_text': 'Version, if applicable.', 'required': False}),
                    2: ('wagtail.blocks.DateBlock', (), {'help_text': 'Date (e.g. creation, publication, etc.'}),
                    3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title for this entry.'}),
                    4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the author(s) for this entry.'}),
                    5: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {
                            'help_text': 'Additional information, e.g. press/place of publication, location of the talk, etc.',
                            'required': False,
                        },
                    ),
                    6: (
                        'wagtail.blocks.RichTextBlock',
                        (),
                        {
                            'editor': 'minimal',
                            'help_text': 'Abstract for this entry, if applicable.',
                            'required': False,
                        },
                    ),
                    7: (
                        'wagtail.blocks.URLBlock',
                        (),
                        {'help_text': 'Related URL, e.g. link to online resource, press site, etc.', 'required': False},
                    ),
                    8: (
                        'wagtail.documents.blocks.DocumentChooserBlock',
                        (),
                        {'help_text': 'Document file (e.g. PDF).', 'required': False},
                    ),
                    9: (
                        'wagtail.blocks.PageChooserBlock',
                        (),
                        {'help_text': 'Add a link to a page on this site.', 'required': False},
                    ),
                    10: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('type', 0),
                                ('version', 1),
                                ('date', 2),
                                ('title', 3),
                                ('author', 4),
                                ('detail', 5),
                                ('abstract', 6),
                                ('url', 7),
                                ('document', 8),
                                ('page', 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        'web.extensions.extras.blocks.uncommented_charblock.UncommentedCharBlock',
                        (),
                        {'required': True},
                    ),
                    12: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False},
                    ),
                    13: ('wagtail.blocks.StructBlock', [[('heading', 11), ('level', 12)]], {}),
                    14: (
                        'wagtail.images.blocks.ImageChooserBlock',
                        (),
                        {'help_text': 'Select the image to display.', 'required': True},
                    ),
                    15: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {'help_text': 'String to use as link anchor.', 'label': 'Image ID', 'required': False},
                    ),
                    16: (
                        'wagtail.blocks.BooleanBlock',
                        (),
                        {'default': True, 'help_text': 'Render caption?', 'label': 'Caption', 'required': False},
                    ),
                    17: (
                        'wagtail.blocks.BooleanBlock',
                        (),
                        {
                            'default': True,
                            'help_text': 'Uncheck to write caption.',
                            'label': 'Caption from file',
                            'required': False,
                        },
                    ),
                    18: (
                        'wagtail.blocks.RichTextBlock',
                        (),
                        {'editor': 'minimal', 'label': 'Caption text', 'required': False},
                    ),
                    19: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [
                                ('left', 'Left-aligned'),
                                ('right', 'Right-aligned'),
                                ('centre', 'Centre-aligned'),
                                ('main', 'Main image (full-width)'),
                            ],
                            'help_text': 'How should the image be aligned on the page?',
                        },
                    ),
                    20: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [
                                ('max', 'Fit within the given dimensions'),
                                ('min', 'Cover the given dimensions'),
                                ('width', 'Reduce width to the given dimension'),
                                ('height', 'Reduce height to the given dimension'),
                                ('scale', 'Resize to the given percentage'),
                                ('fill', 'Resize and crop to the given dimensions'),
                                ('background', 'As background with given parameters'),
                            ],
                            'help_text': 'Resize using a <a href="https://docs.wagtail.org/en/v2.13.5/topics/images.html" target="_blank">built-in rule</a>            or use as background of &lt;div&gt; with fixed dimensions.',
                            'required': False,
                        },
                    ),
                    21: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {
                            'help_text': 'Width x height, e.g. "400x200".',
                            'required': False,
                            'validators': [web.extensions.images.blocks.inline_image.validate_dimensions],
                        },
                    ),
                    22: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {
                            'help_text': 'CSS parameters to be used if the image is displayed as a background, e.g. "no-repeat top/cover".',
                            'label': 'CSS parameters',
                            'required': False,
                        },
                    ),
                    23: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('image', 14),
                                ('image_id', 15),
                                ('show_caption', 16),
                                ('use_file_caption', 17),
                                ('caption', 18),
                                ('alignment', 19),
                                ('resize_rule', 20),
                                ('dimensions', 21),
                                ('parameters', 22),
                            ]
                        ],
                        {},
                    ),
                    24: ('wagtail.blocks.PageChooserBlock', (), {}),
                    25: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal', 'icon': 'openquote'}),
                    26: ('wagtail.blocks.CharBlock', (), {'help_text': 'Subsection title.', 'label': 'Title'}),
                    27: (
                        'wagtail.blocks.BooleanBlock',
                        (),
                        {'default': False, 'help_text': 'Render closed.', 'required': False},
                    ),
                    28: (
                        'wagtail.blocks.BooleanBlock',
                        (),
                        {'default': False, 'help_text': 'Render indented.', 'label': 'Minor', 'required': False},
                    ),
                    29: ('web.extensions.bibliography.blocks.BibliographyChooserBlock', (), {}),
                    30: ('wagtail.images.blocks.ImageChooserBlock', (), {}),
                    31: ('web.extensions.images.blocks.carousel.CarouselBlock', (30,), {}),
                    32: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Embed code for the chart.'}),
                    33: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [('left', 'Left-aligned'), ('right', 'Right-aligned'), ('full', 'Full-width')],
                            'help_text': 'How should the chart be aligned on the page?',
                        },
                    ),
                    34: ('wagtail.blocks.StructBlock', [[('html', 32), ('alignment', 33)]], {}),
                    35: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [
                                ('bash', 'Bash/Shell'),
                                ('css', 'CSS'),
                                ('diff', 'diff'),
                                ('html', 'HTML'),
                                ('javascript', 'Javascript'),
                                ('json', 'JSON'),
                                ('python', 'Python'),
                                ('scss', 'SCSS'),
                                ('yaml', 'YAML'),
                            ],
                            'identifier': 'language',
                            'label': 'Language',
                        },
                    ),
                    36: ('wagtail.blocks.TextBlock', (), {'identifier': 'code', 'label': 'Code'}),
                    37: ('wagtail.blocks.StructBlock', [[('language', 35), ('code', 36)]], {}),
                    38: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'}),
                    39: ('wagtail.blocks.StructBlock', [[]], {}),
                    40: ('wagtail.blocks.RawHTMLBlock', (), {}),
                    41: (
                        'wagtail.contrib.table_block.blocks.TableBlock',
                        (),
                        {
                            'form_classname': 'table-block',
                            'icon': 'table-cells',
                            'table_options': {
                                'autoColumnSize': False,
                                'colHeaders': False,
                                'contextMenu': [
                                    'row_above',
                                    'row_below',
                                    '---------',
                                    'col_left',
                                    'col_right',
                                    '---------',
                                    'remove_row',
                                    'remove_col',
                                    '---------',
                                    'undo',
                                    'redo',
                                    '---------',
                                    'copy',
                                    'cut',
                                    '---------',
                                    'alignment',
                                ],
                                'editor': 'text',
                                'height': 108,
                                'language': 'en-US',
                                'minSpareRows': 0,
                                'renderer': 'text',
                                'rowHeaders': False,
                                'startCols': 3,
                                'startRows': 3,
                                'stretchH': 'all',
                            },
                        },
                    ),
                    42: ('wagtail.blocks.CharBlock', (), {}),
                    43: ('wagtail.blocks.FloatBlock', (), {}),
                    44: ('wagtail.blocks.RichTextBlock', (), {}),
                    45: ('wagtail.images.blocks.ImageBlock', [], {}),
                    46: (
                        'wagtail.contrib.typed_table_block.blocks.TypedTableBlock',
                        [[('text', 42), ('numeric', 43), ('rich_text', 44), ('image', 45)]],
                        {'label': 'Table (typed)'},
                    ),
                    47: ('wagtail.blocks.StructBlock', [[('body', 44)]], {}),
                    48: (
                        'wagtail.blocks.StreamBlock',
                        [
                            [
                                ('bibliography', 29),
                                ('carousel', 31),
                                ('chart_embed', 34),
                                ('code', 37),
                                ('document', 10),
                                ('embed', 38),
                                ('footnotes_placemarker', 39),
                                ('heading', 13),
                                ('html', 40),
                                ('inline_image', 23),
                                ('page', 24),
                                ('pullquote', 25),
                                ('table', 41),
                                ('table_typed', 46),
                                ('text', 44),
                                ('text_expandable', 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        'wagtail.blocks.StructBlock',
                        [[('subsection', 26), ('collapsed', 27), ('minor_heading', 28), ('body', 48)]],
                        {},
                    ),
                    50: (
                        'wagtail.blocks.StreamBlock',
                        [
                            [
                                ('bibliography', 29),
                                ('carousel', 31),
                                ('chart_embed', 34),
                                ('code', 37),
                                ('document', 10),
                                ('embed', 38),
                                ('footnotes_placemarker', 39),
                                ('heading', 13),
                                ('html', 40),
                                ('inline_image', 23),
                                ('page', 24),
                                ('pullquote', 25),
                                ('table', 41),
                                ('table_typed', 46),
                                ('text', 44),
                                ('text_expandable', 47),
                                ('nested_subsection', 49),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        'wagtail.blocks.StructBlock',
                        [[('subsection', 26), ('collapsed', 27), ('minor_heading', 28), ('body', 50)]],
                        {},
                    ),
                    52: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [('members', 'Manual list'), ('role', 'Role-based list')],
                            'help_text': 'Select how you wish to define the list.',
                            'label': 'List mode',
                        },
                    ),
                    53: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': [
                                ('name', 'Name'),
                                ('role', 'Role'),
                                ('affiliation', 'Affiliation'),
                                ('user__date_joined', 'Join date (oldest first)'),
                                ('-user__date_joined', 'Join date (latest first)'),
                            ],
                            'help_text': 'Select how the list should be ordered.',
                            'label': 'Order',
                        },
                    ),
                    54: (
                        'wagtail.blocks.MultipleChoiceBlock',
                        [],
                        {
                            'choices': web.extensions.team.blocks.get_member_choices,
                            'help_text': 'Manually select team members to include in the list.',
                            'label': 'Members',
                            'required': False,
                        },
                    ),
                    55: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': web.extensions.team.blocks.get_role_choices,
                            'help_text': 'Select a role to define the list (all members with that role will be included).',
                            'label': 'Role',
                            'required': False,
                        },
                    ),
                    56: (
                        'wagtail.blocks.StructBlock',
                        [[('mode', 52), ('order', 53), ('members', 54), ('role', 55)]],
                        {},
                    ),
                    57: ('wagtail.blocks.RichTextBlock', (), {'editor': 'minimal'}),
                },
                null=True,
            ),
        ),
    ]
