# Generated by Django 5.1.4 on 2025-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_alter_people_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='analytics_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='analytics_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='analytics_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='analytics_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='analytics_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='analytics_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
