# Generated by Django 5.1.4 on 2026-01-31 14:15

from django.db import migrations

import web.extensions.block_registry


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0006_alter_bibliography_body_alter_collection_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='collections',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='featuredinventory',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='featuredobject',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='features',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=web.extensions.block_registry.RegistryStreamField([], block_lookup={}, null=True),
        ),
    ]
