export const columnMap = {
  name: {
    label: "Name",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: true,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  noFolios: {
    label: "No. Folios",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
    autoWidth: true,
  },
  owner: {
    label: "Owner",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  isPrivate: {
    label: "Private",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    autoWidth: true,
  },
  locale: {
    label: "Locale(s)",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
  },
  recordType: {
    label: "Record Type",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  date: {
    label: "Date",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  language: {
    label: "Languages",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  status: {
    label: "Status",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  helpFlag: {
    label: "Help",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    autoWidth: true,
  },
  activity: {
    label: "Activity",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
  },
  isPublic: {
    label: "Public",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    autoWidth: true,
  },
  creationUser: {
    label: "Created by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  creationTimestamp: {
    label: "Created on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  modificationUser: {
    label: "Modified by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  modificationTimestamp: {
    label: "Modified on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
};
