services:
  dalme.web:
    # platform: linux/amd64
    image: "web:eb"
    container_name: dalme.eb
    build:
      context: ./
      dockerfile: "./config/eb/Dockerfile.web"
    env_file:
      - "./config/eb/env.web.eb"
    volumes:
      - ./dalme_api:/opt/app/dalme_api
      - ./dalme_app:/opt/app/dalme_app
      - ./dalme_public:/opt/app/dalme_public
      - ./templates:/opt/app/templates
    command: >
      bash -c "python manage.py collectstatic --noinput && \
      python manage.py compress --verbosity=0 && \
      ./wait-for-it.sh db:3306 -- gunicorn -c gunicorn.conf.py dalme.wsgi"
    depends_on:
      - dalme.db
    networks:
      - app-network
    ports:
      - "8443"
    restart: unless-stopped
    stdin_open: true
    tty: true

  dalme.db:
    platform: linux/amd64
    image: mysql:8.0.19
    container_name: dalme.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dalme
      MYSQL_PASSWORD: dalme
      MYSQL_DATABASE: dalme_db
      MYSQL_HOST: db
    volumes:
      - "./config/eb/my.cnf:/etc/mysql/conf.d/my.cnf:ro"
      - ./sql/mysql_eb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306"
    cap_add:
      - SYS_NICE

  dalme.proxy:
    image: nginx:mainline
    container_name: dalme.proxy
    env_file:
      - "./config/eb/env.web.eb"
    volumes:
      - "./config/eb/nginx:/etc/nginx/conf.d"
      - ./ssl-certs:/var/certs
      - assets:/static
    networks:
      - app-network
    depends_on:
      - dalme.web
    ports:
      - "8000:443"

volumes:
  assets:
  db-data:

networks:
  app-network:
    driver: bridge
