services:
  dalme.web:
    image: "web:dev"
    container_name: dalme.web
    build:
      context: ./
      dockerfile: "./config/dev/Dockerfile.web"
    env_file:
      - "./config/dev/env.web.dev"
    volumes:
      - ./dalme_api:/opt/app/dalme_api
      - ./dalme_app:/opt/app/dalme_app
      - ./dalme_public:/opt/app/dalme_public
      - ./templates:/opt/app/templates
    command: >
      bash -c "./wait-for-it.sh db:5432 -- gunicorn -c gunicorn.conf.py dalme.wsgi"
    depends_on:
      - dalme.db
    networks:
      - app-network
    ports:
      - "8443"
    restart: unless-stopped
    stdin_open: true
    tty: true

  dalme.ui:
    image: "ui:dev"
    container_name: dalme.ui
    build:
      context: ./
      dockerfile: "./config/dev/Dockerfile.ui"
    env_file:
      - "./config/dev/env.ui.dev"
    volumes:
      - ./dalme_ui/src:/opt/ui/src
    networks:
      - app-network
    ports:
      - "3000"

  dalme.db:
    image: postgres
    container_name: dalme.db
    environment:
      POSTGRES_USER: dalme
      POSTGRES_PASSWORD: dalme
      POSTGRES_DB: dalme
      POSTGRES_HOST: db
    volumes:
      - "./config/dev/postgresql.conf:/etc/postgresql/postgresql.conf"
      - ./sql/postgresql:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    cap_add:
      - SYS_NICE

  dalme.proxy:
    image: nginx:mainline
    container_name: dalme.proxy
    env_file:
      - "./config/dev/env.web.dev"
    volumes:
      - "./config/dev/nginx:/etc/nginx/conf.d"
      - ./ssl-certs:/var/certs
      - assets:/static
    networks:
      - app-network
    depends_on:
      - dalme.web
    ports:
      - "8000:443"

volumes:
  assets:
  pgdata:

networks:
  app-network:
    driver: bridge
