x-aws-loadbalancer: "dalme2-beta-lb"
x-aws-vpc: "vpc-5f496427"
# x-aws-cluster: "ClusterName"
services:
  dalme.web:
    image: "916099420556.dkr.ecr.us-east-1.amazonaws.com/dalme-prod:web"
    container_name: dalme.web
    secrets:
      - dalme-secrets
    build:
      context: ./
      dockerfile: "./config/prod/Dockerfile.web"
    command: >
      bash -c "python manage.py makemigrations &&
              python manage.py migrate --noinput &&
              /usr/local/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - target: 8443
        x-aws-protocol: http
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2Gb
      x-aws-autoscaling:
        min: 1
        max: 3
        cpu: 85

  dalme.ui:
    image: "916099420556.dkr.ecr.us-east-1.amazonaws.com/dalme-prod:ui"
    container_name: dalme.ui
    secrets:
      - dalme-secrets
    build:
      context: ./
      dockerfile: "./config/prod/Dockerfile.ui"
    depends_on:
      - dalme.web
    ports:
      - target: 3000
        x-aws-protocol: http

  dalme.proxy:
    image: "916099420556.dkr.ecr.us-east-1.amazonaws.com/dalme-prod:proxy"
    container_name: dalme.proxy
    secrets:
      - dalme-secrets
    build:
      context: ./
      dockerfile: "./config/prod/Dockerfile.proxy"
    depends_on:
      - dalme.web
    ports:
      - "0.0.0.0:80:80"
    restart: on-failure

secrets:
  dalme-secrets:
    name: "arn:aws:secretsmanager:us-east-1:916099420556:secret:dalme2/beta-0YUCdx"
    external: true
    x-aws-keys:
      - "*"

networks:
  default:

# x-aws-logs_retention: 10
# x-aws-cloudformation:
#   Resources:
#     WebappTCP80TargetGroup:
#       Properties:
#         HealthCheckPath: /health
#         Matcher:
#           HttpCode: 200-499
