# https://github.com/charliermarsh/ruff#configuration
[tool.ruff]
ignore = [
  "E501",   # line length
  "D100",   # missing docstring in public module
  "D104",   # missing docstring in public package
  "FBT002", # boolean default in function definition
]
ignore-init-module-imports = true
line-length = 120 # to match black's config
select = [
  "A",
  "ARG",
  "B",
  "BLE",
  "C4",
  "C90",
  "COM",
  "D",
  "DTZ",
  "DJ",
  "E",
  "EM",
  "F",
  "FBT",
  "FLY",
  "G",
  "I",
  "ICN",
  "INP",
  "INT",
  "ISC",
  "N",
  "PGH",
  "PIE",
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  "PT",
  "PTH",
  # "Q",  # Implies double-quotes.
  "RET",
  "RUF",
  "RSE",
  "SLF",
  "SIM",
  "T",
  "T10",
  "T20",
  # "TD", # crashing for GHP
  "TID",
  "TRY",
  "UP",
  "W",
]
target-version = "py311"

[tool.ruff.isort]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "django",
  "first-party",
  "local-folder",
]

[tool.ruff.isort.sections]
django = ["django"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402"] # ignore import violations in init files

[tool.black]
line-length = 120
target-version = ["py311"]
skip-string-normalization = true
