# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import dalme_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platonicconcept',
            name='id',
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='_id',
            field=models.CharField(db_column='id', default=dalme_app.models.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
