# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0002_auto_20170531_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platonicconcept',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='creation_timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='creation_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='modification_timestamp',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='modification_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
