# Generated by Django 2.0.5 on 2018-06-20 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0002_attribute_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(db_column='attribute_type', on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Attribute_type'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent_source',
            field=models.ForeignKey(db_column='parent_source', null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Source'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Content_type'),
        ),
    ]
