# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 19:56
from __future__ import unicode_literals

import dalme_app.modelTemplates
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0007_platonicconcept_getty_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('type_csl', models.CharField(blank=True, max_length=255, null=True)),
                ('type_zotero', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.SourceType'),
        ),
    ]
