# Generated by Django 2.1.7 on 2019-02-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0008_auto_20190218_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_list',
            name='extra_headers',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
