# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 20:33
from __future__ import unicode_literals

import dalme_app.modelTemplates
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0008_auto_20170606_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAttribute',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceAttributeType',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type_dublin_core', models.CharField(blank=True, max_length=255, null=True)),
                ('type_csl', models.CharField(blank=True, max_length=255, null=True)),
                ('type_zotero', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('dropdown_content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='source',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='dropdown_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='parent_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_parent', to='dalme_app.Source'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='dropdown_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sourceattribute',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Source'),
        ),
        migrations.AddField(
            model_name='sourceattribute',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.SourceAttributeType'),
        ),
    ]
