# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-06 20:46
from __future__ import unicode_literals

import dalme_app.modelTemplates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0009_auto_20170606_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platonicconcept',
            name='_id',
            field=models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='_id',
            field=models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
