# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-07 21:25
from __future__ import unicode_literals

import dalme_app.modelTemplates
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0010_auto_20170606_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='concept_components',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='concepts',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='external_lemma_attributes',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='external_lemmata',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inventories',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inventory_attributes',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='inventory_versions',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='dalme_app.inventories')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='leaf_images',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='lines',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('inventory_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_version', to='dalme_app.inventory_versions')),
                ('leaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_leaf', to='dalme_app.leaves')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='phrase_parts',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='phrases',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('parent_phrase', models.CharField(max_length=36)),
                ('_type', models.CharField(max_length=36)),
                ('platonic_concept', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='predicate_labels',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.CharField(max_length=36)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='predicates',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('uri', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='reference_attributes',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='references',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('foreign_id', models.CharField(max_length=36)),
                ('_type', models.CharField(max_length=36)),
                ('source_id', models.CharField(max_length=36)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='repository',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='repository_attributes',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=32)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_attribute_subject', to='dalme_app.references')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='source_attributes',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=32)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sources',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='superlemma_components',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('predicate', models.CharField(max_length=32)),
                ('_object', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='superlemmata',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('temp', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(max_length=255)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_line', to='dalme_app.lines')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='source',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='target',
        ),
        migrations.RemoveField(
            model_name='source',
            name='parent_source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='sourceattribute',
            name='source',
        ),
        migrations.RemoveField(
            model_name='sourceattribute',
            name='type',
        ),
        migrations.DeleteModel(
            name='PlatonicConcept',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='SourceAttribute',
        ),
        migrations.DeleteModel(
            name='SourceAttributeType',
        ),
        migrations.DeleteModel(
            name='SourceType',
        ),
        migrations.AddField(
            model_name='superlemma_components',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superlemma_component_subject', to='dalme_app.superlemmata'),
        ),
        migrations.AddField(
            model_name='reference_attributes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_attribute_subject', to='dalme_app.references'),
        ),
        migrations.AddField(
            model_name='predicate_labels',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_predicate', to='dalme_app.predicates'),
        ),
        migrations.AddField(
            model_name='phrase_parts',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_part_phrase', to='dalme_app.phrases'),
        ),
        migrations.AddField(
            model_name='phrase_parts',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrase_part_token', to='dalme_app.tokens'),
        ),
        migrations.AddField(
            model_name='leaf_images',
            name='leaf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_leaf', to='dalme_app.leaves'),
        ),
        migrations.AddField(
            model_name='external_lemma_attributes',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_lemma_subject', to='dalme_app.external_lemmata'),
        ),
        migrations.AddField(
            model_name='concept_components',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_component_subject', to='dalme_app.concepts'),
        ),
    ]
