# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-05 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0020_auto_20170805_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='par_tokens',
            name='span_start',
        ),
    ]
