# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-06 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0025_auto_20170806_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='error_messages',
            old_name='_code',
            new_name='e_code',
        ),
        migrations.RenameField(
            model_name='error_messages',
            old_name='_level',
            new_name='e_level',
        ),
        migrations.RenameField(
            model_name='error_messages',
            old_name='_text',
            new_name='e_text',
        ),
        migrations.RenameField(
            model_name='error_messages',
            old_name='_type',
            new_name='e_type',
        ),
    ]
