# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-07 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0027_auto_20170806_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='par_objects',
            fields=[
                ('obj_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ont_class', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('terms', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=64)),
                ('room', models.CharField(max_length=64)),
            ],
        ),
    ]
