# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-28 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0028_par_objects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inventory_attributes',
        ),
        migrations.DeleteModel(
            name='repository',
        ),
        migrations.DeleteModel(
            name='source_attributes',
        ),
        migrations.DeleteModel(
            name='sources',
        ),
        migrations.DeleteModel(
            name='concept_components',
        ),
        migrations.DeleteModel(
            name='concepts',
        ),
        migrations.DeleteModel(
            name='external_lemma_attributes',
        ),
        migrations.DeleteModel(
            name='external_lemmata',
        ),
        migrations.DeleteModel(
            name='inventories',
        ),
        migrations.DeleteModel(
            name='inventory_versions',
        ),
        migrations.DeleteModel(
            name='leaf_images',
        ),
        migrations.DeleteModel(
            name='leaves',
        ),
        migrations.DeleteModel(
            name='lines',
        ),
        migrations.DeleteModel(
            name='phrase_parts',
        ),
        migrations.DeleteModel(
            name='phrases',
        ),
        migrations.DeleteModel(
            name='predicate_labels',
        ),
        migrations.DeleteModel(
            name='predicates',
        ),
        migrations.DeleteModel(
            name='reference_attributes',
        ),
        migrations.DeleteModel(
            name='references',
        ),
        migrations.DeleteModel(
            name='repository_attributes',
        ),
        migrations.DeleteModel(
            name='superlemma_components',
        ),
        migrations.DeleteModel(
            name='superlemmata',
        ),
        migrations.DeleteModel(
            name='tokens',
        ),
    ]
