# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0029_auto_20180428_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='agents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attribute_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('attribute_type', models.IntegerField()),
                ('content_id', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes_DATE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.DateField()),
                ('value_day', models.IntegerField()),
                ('value_month', models.IntegerField()),
                ('value_year', models.IntegerField()),
                ('attribute_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes_DBR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=36)),
                ('attribute_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes_INT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.IntegerField()),
                ('attribute_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes_STR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.CharField(max_length=255)),
                ('attribute_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='attributes_TXT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('value', models.TextField()),
                ('attribute_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='concepts',
            fields=[
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('getty_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='content_classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='content_types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('content_class', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='content_types_x_attribute_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.IntegerField()),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attribute_types')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.content_types')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='headwords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('word', models.CharField(max_length=50)),
                ('full_lemma', models.CharField(max_length=255)),
                ('concept_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.concepts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='identity_phrases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('phrase', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='identity_phrases_x_entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('entity_id', models.CharField(max_length=36)),
                ('identity_phrase_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.identity_phrases')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='object_attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('concept_id', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='object_phrases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('phrase', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='objects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('concept_id', models.CharField(max_length=36)),
                ('object_phrase_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.object_phrases')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=15)),
                ('dam_id', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sources',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=15)),
                ('parent_source', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='tokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('raw_token', models.CharField(max_length=255)),
                ('clean_token', models.CharField(max_length=55)),
                ('order', models.IntegerField()),
                ('flags', models.CharField(max_length=10)),
                ('object_phrase_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.object_phrases')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='transcriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('transcription', models.TextField()),
                ('source_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.sources')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='word_forms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('normalized_form', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=255)),
                ('headword_id', models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.headwords')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tokens',
            name='word_form_id',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.word_forms'),
        ),
        migrations.AddField(
            model_name='pages',
            name='source_id',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.sources'),
        ),
        migrations.AddField(
            model_name='object_phrases',
            name='transcription_id',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.transcriptions'),
        ),
        migrations.AddField(
            model_name='object_attributes',
            name='object_id',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.objects'),
        ),
        migrations.AddField(
            model_name='identity_phrases',
            name='transcription_id',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.transcriptions'),
        ),
    ]
