# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-29 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0030_auto_20180428_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='par_folios',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='par_inventories',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='par_tokens',
            name='_id',
        ),
        migrations.AddField(
            model_name='error_messages',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='error_messages',
            name='creation_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='error_messages',
            name='modification_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='error_messages',
            name='modification_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='par_folios',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='par_inventories',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='par_tokens',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
