# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0031_auto_20180429_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_messages2',
            fields=[
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('e_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('e_level', models.IntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (25, 'SUCCESS'), (30, 'WARNING'), (40, 'ERROR')])),
                ('e_text', models.TextField()),
                ('e_type', models.IntegerField(choices=[(1, 'MODAL'), (2, 'NOTIFICATION')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
