# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-29 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0033_auto_20180429_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='is_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
