# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-29 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0034_sources_is_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_types',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute_types',
            name='short_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='content_classes',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content_classes',
            name='short_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='content_types',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='content_types',
            name='short_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='headwords',
            name='word',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='sources',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sources',
            name='short_name',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='word_forms',
            name='normalized_form',
            field=models.CharField(max_length=55),
        ),
    ]
