# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-29 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0035_auto_20180429_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_types',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='content_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='attributes_date',
            name='attribute_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_dbr',
            name='attribute_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_dbr',
            name='value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='attributes_int',
            name='attribute_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_str',
            name='attribute_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_txt',
            name='attribute_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.attributes'),
        ),
        migrations.AlterField(
            model_name='concepts',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='content_classes',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content_types',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='headwords',
            name='concept_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.concepts'),
        ),
        migrations.AlterField(
            model_name='identity_phrases',
            name='transcription_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.transcriptions'),
        ),
        migrations.AlterField(
            model_name='identity_phrases_x_entities',
            name='entity_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='identity_phrases_x_entities',
            name='identity_phrase_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.identity_phrases'),
        ),
        migrations.AlterField(
            model_name='object_attributes',
            name='concept_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='object_attributes',
            name='object_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.objects'),
        ),
        migrations.AlterField(
            model_name='object_phrases',
            name='transcription_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.transcriptions'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='concept_id',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='objects',
            name='object_phrase_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.object_phrases'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='source_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.sources'),
        ),
        migrations.AlterField(
            model_name='sources',
            name='parent_source',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='object_phrase_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.object_phrases'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='word_form_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.word_forms'),
        ),
        migrations.AlterField(
            model_name='transcriptions',
            name='source_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.sources'),
        ),
        migrations.AlterField(
            model_name='word_forms',
            name='headword_id',
            field=models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.headwords'),
        ),
    ]
