# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0037_auto_20180501_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes_date',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
