# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0038_auto_20180501_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='parent_source',
            field=models.UUIDField(null=True),
        ),
    ]
