# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-05-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0039_auto_20180505_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='parent_source',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
