# Generated by Django 2.0.5 on 2018-06-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0050_auto_20180528_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sources',
            new_name='Source',
        ),
        migrations.AlterField(
            model_name='attributes_date',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_dbr',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_int',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_str',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attributes'),
        ),
        migrations.AlterField(
            model_name='attributes_txt',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attributes'),
        ),
        migrations.AlterField(
            model_name='content_types_x_attribute_types',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Attribute_types'),
        ),
        migrations.AlterField(
            model_name='content_types_x_attribute_types',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Content_types'),
        ),
        migrations.AlterField(
            model_name='headwords',
            name='concept_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Concepts'),
        ),
        migrations.AlterField(
            model_name='identity_phrases',
            name='transcription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Transcriptions'),
        ),
        migrations.AlterField(
            model_name='identity_phrases_x_entities',
            name='identity_phrase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Identity_phrases'),
        ),
        migrations.AlterField(
            model_name='object_attributes',
            name='object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Objects'),
        ),
        migrations.AlterField(
            model_name='object_phrases',
            name='transcription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Transcriptions'),
        ),
        migrations.AlterField(
            model_name='objects',
            name='object_phrase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Object_phrases'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='object_phrase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Object_phrases'),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='word_form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Word_forms'),
        ),
        migrations.AlterField(
            model_name='word_forms',
            name='headword_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Headwords'),
        ),
    ]
