# Generated by Django 5.0.4 on 2024-12-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Gradient',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('colour_1', models.CharField(max_length=9)),
                ('colour_2', models.CharField(max_length=9)),
                ('angle', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
