# Generated by Django 2.2.4 on 2020-03-30 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0142_auto_20200323_1812'),
        ('dalme_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='set',
            name='description',
        ),
        migrations.AddField(
            model_name='collection',
            name='source_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_collections', to='dalme_app.Set'),
        ),
        migrations.AddField(
            model_name='set',
            name='source_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_sets', to='dalme_app.Set'),
        ),
    ]
