# Generated by Django 3.1.2 on 2020-12-17 17:18

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='collections',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='essay',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='features',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='flat',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='home',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AddField(
            model_name='section',
            name='header_position',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='top', help_text='Position of the header image within its container.', max_length=6),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social',
            field=wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('fa_icon', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('css_class', wagtail.core.blocks.CharBlock(required=False))]))], null=True),
        ),
    ]
