# Generated by Django 4.2.1 on 2023-05-18 16:01

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.images.models

from django.db import migrations

import dalme_public.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='collections',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='customrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='dalmeimage',
            name='file',
            field=wagtail.images.models.WagtailImageField(
                height_field='height',
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name='file',
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='essay',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='explorepage',
            name='text_after',
            field=wagtail.fields.StreamField(
                [
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='explorepage',
            name='text_before',
            field=wagtail.fields.StreamField(
                [
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='featuredinventory',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='featuredobject',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='features',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='flat',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='footer',
            name='pages',
            field=wagtail.fields.StreamField(
                [
                    (
                        'page',
                        wagtail.blocks.StructBlock(
                            [('title', wagtail.blocks.CharBlock()), ('page', wagtail.blocks.PageChooserBlock())]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='footer',
            name='social',
            field=wagtail.fields.StreamField(
                [
                    (
                        'social',
                        wagtail.blocks.StructBlock(
                            [
                                ('fa_icon', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('css_class', wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='home',
            name='banners',
            field=wagtail.fields.StreamField(
                [
                    (
                        'banners',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.TextBlock()),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('start_date', wagtail.blocks.DateBlock()),
                                ('end_date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='home',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='home',
            name='sponsors',
            field=wagtail.fields.StreamField(
                [
                    (
                        'sponsors',
                        wagtail.blocks.StructBlock(
                            [('logo', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.blocks.URLBlock())]
                        ),
                    )
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='searchpage',
            name='help_content',
            field=wagtail.fields.StreamField(
                [('text', wagtail.blocks.RichTextBlock()), ('html', wagtail.blocks.RawHTMLBlock())],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'chart_embed',
                        wagtail.blocks.StructBlock(
                            [
                                ('html', wagtail.blocks.RawHTMLBlock()),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('left', 'Left-aligned'),
                                            ('right', 'Right-aligned'),
                                            ('full', 'Full-width'),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock(required=False)),
                                ('institution', wagtail.blocks.CharBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                                ('minor_heading', wagtail.blocks.BooleanBlock(default=False, required=False)),
                            ]
                        ),
                    ),
                    ('subsection_end_marker', wagtail.blocks.StructBlock([])),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
