# Generated by Django 3.1.2 on 2020-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='collections',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='essay',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='features',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='flat',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='home',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
        migrations.AddField(
            model_name='section',
            name='citable',
            field=models.BooleanField(default=False, help_text='Check this box to show the "Cite" menu for this page.'),
        ),
    ]
