# Generated by Django 2.2.4 on 2020-07-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('dalme_public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='learn_more_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
