# Generated by Django 2.2.4 on 2020-04-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0002_auto_20200330_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
