# Generated by Django 4.2.1 on 2023-06-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ('dalme_app', '0013_data_m_local_values'),
        ('dalme_public', '0002_alter_bibliography_body_alter_collection_body_and_more'),
    ]

    run_before = [
        ('dalme_app', '0014_remove_unused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source_set',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='public_collections',
                to='dalme_app.collection',
            ),
        ),
        migrations.AlterField(
            model_name='essay',
            name='source_set',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional, select a particular public set for the source associated with this essay. The source must be a member of the set chosen or the page will not validate.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='essays',
                to='dalme_app.collection',
            ),
        ),
        migrations.AlterField(
            model_name='featuredinventory',
            name='source_set',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional, select a particular public set for the source associated with this inventory. The source must be a member of the set chosen or the page will not validate.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='featured_inventories',
                to='dalme_app.collection',
            ),
        ),
        migrations.AlterField(
            model_name='featuredobject',
            name='source_set',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional, select a particular public set for the source associated with this object. The source must be a member of the set chosen or the page will not validate.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='featured_objects',
                to='dalme_app.collection',
            ),
        ),
    ]
