# Generated by Django 4.2.2 on 2023-06-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ('dalme_app', '0015_create_options'),
        ('dalme_public', '0003_sets_to_collections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='essays',
                to='dalme_app.record',
            ),
        ),
        migrations.AlterField(
            model_name='featuredinventory',
            name='source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='featured_inventories',
                to='dalme_app.record',
            ),
        ),
        migrations.AlterField(
            model_name='featuredobject',
            name='source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='featured_objects',
                to='dalme_app.record',
            ),
        ),
    ]
