# Generated by Django 2.2.4 on 2020-06-16 17:21

import dalme_public.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('dalme_app', '0143_auto_20200408_1214'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('dalme_public', '0003_auto_20200616_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('short_title', models.CharField(blank=True, help_text='An optional short title that will be displayed in certain contexts.', max_length=63, null=True)),
                ('body', wagtail.core.fields.StreamField([('main_image', dalme_public.blocks.MainImageBlock()), ('inline_image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('pullquote', wagtail.core.blocks.RichTextBlock(icon='openquote')), ('document', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('abstract', wagtail.core.blocks.CharBlock()), ('version', wagtail.core.blocks.FloatBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('date', wagtail.core.blocks.DateBlock())])), ('person', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('job', wagtail.core.blocks.CharBlock()), ('institution', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('external_resource', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('info', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock()), ('date', wagtail.core.blocks.DateBlock())])), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')), ('html', wagtail.core.blocks.RawHTMLBlock()), ('subsection', wagtail.core.blocks.StructBlock([('subsection', wagtail.core.blocks.CharBlock()), ('collapsed', wagtail.core.blocks.BooleanBlock(default=True, required=False))]))], null=True)),
                ('header_image', models.ForeignKey(blank=True, help_text='The image that will display in the header.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dalme_public.DALMEImage')),
                ('source_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_collections', to='dalme_app.Set')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='sets',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.AddField(
            model_name='corpus',
            name='collections',
            field=modelcluster.fields.ParentalManyToManyField(to='dalme_public.Collection'),
        ),
    ]
