# Generated by Django 3.1.2 on 2020-10-26 16:18

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0003_change_citable_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHelpBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], null=True)),
            ],
        ),
    ]
