# Generated by Django 4.2.2 on 2023-12-18 11:12
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0029_folio_recordgroup_record_folio_record_and_more'),
        ('dalme_public', '0004_alter_source_links'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='essay',
                    name='source',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='essays',
                        to='ida.record',
                    ),
                ),
                migrations.AlterField(
                    model_name='featuredinventory',
                    name='source',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='featured_inventories',
                        to='ida.record',
                    ),
                ),
                migrations.AlterField(
                    model_name='featuredobject',
                    name='source',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='featured_objects',
                        to='ida.record',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
