# Generated by Django 3.1.2 on 2021-01-11 16:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0004_auto_20210110_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='banners',
            field=wagtail.core.fields.StreamField([('banners', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('info', wagtail.core.blocks.TextBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('start_date', wagtail.core.blocks.DateBlock()), ('end_date', wagtail.core.blocks.DateBlock())]))], null=True),
        ),
    ]
