# Generated by Django 3.1.2 on 2021-01-11 16:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_public', '0004_auto_20210110_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='banners',
            field=wagtail.fields.StreamField(
                [
                    (
                        'banners',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.TextBlock()),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('start_date', wagtail.blocks.DateBlock()),
                                ('end_date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
