# Generated by Django 3.1.2 on 2020-10-31 18:44

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0004_auto_20201026_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreMapText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text_before', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], null=True)),
                ('text_after', wagtail.core.fields.StreamField([('inline_image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media'))], null=True)),
            ],
        )
    ]
