# Generated by Django 2.2.4 on 2020-06-17 18:54

from django.db import migrations
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0005_auto_20200617_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='sponsors',
            field=wagtail.core.fields.StreamField([('sponsors', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
    ]
