# Generated by Django 3.1.2 on 2021-01-15 21:09

import dalme_public.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_public', '0007_auto_20210115_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='collection',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='collections',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='essay',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='explorepage',
            name='text_after',
            field=wagtail.fields.StreamField(
                [
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='featuredinventory',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='featuredobject',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='features',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='flat',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='home',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='section',
            name='body',
            field=wagtail.fields.StreamField(
                [
                    ('main_image', dalme_public.blocks.MainImageBlock()),
                    ('carousel', dalme_public.blocks.CarouselBlock(wagtail.images.blocks.ImageChooserBlock())),
                    (
                        'inline_image',
                        wagtail.blocks.StructBlock(
                            [
                                ('image', wagtail.images.blocks.ImageChooserBlock()),
                                ('caption', wagtail.blocks.RichTextBlock(required=False)),
                                (
                                    'alignment',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[('left', 'Left-aligned'), ('right', 'Right-aligned')]
                                    ),
                                ),
                                ('show_caption', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                    ('text', wagtail.blocks.RichTextBlock()),
                    ('heading', wagtail.blocks.CharBlock()),
                    ('pullquote', wagtail.blocks.RichTextBlock(icon='openquote')),
                    ('page', wagtail.blocks.PageChooserBlock()),
                    (
                        'bibliography',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'collection',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('A4QHN348', 'Editions'),
                                            ('BKW2PVCM', 'Glossaries and dictionaries'),
                                            ('QM9AZNT3', 'Methodology'),
                                            ('SLIT6LID', 'Studies'),
                                            ('FRLVXUWL', 'Other resources'),
                                        ]
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        'document',
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    'type',
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ('document', 'Document'),
                                            ('publication', 'Publication'),
                                            ('talk', 'Talk'),
                                        ]
                                    ),
                                ),
                                ('title', wagtail.blocks.CharBlock()),
                                ('abstract', wagtail.blocks.CharBlock(required=False)),
                                ('author', wagtail.blocks.CharBlock()),
                                ('detail', wagtail.blocks.CharBlock(required=False)),
                                ('version', wagtail.blocks.FloatBlock(required=False)),
                                ('document', wagtail.documents.blocks.DocumentChooserBlock(required=False)),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('page', wagtail.blocks.PageChooserBlock(required=False)),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    (
                        'person',
                        wagtail.blocks.StructBlock(
                            [
                                ('name', wagtail.blocks.CharBlock()),
                                ('job', wagtail.blocks.CharBlock()),
                                ('institution', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock(required=False)),
                                ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        'external_resource',
                        wagtail.blocks.StructBlock(
                            [
                                ('title', wagtail.blocks.CharBlock()),
                                ('info', wagtail.blocks.CharBlock()),
                                ('url', wagtail.blocks.URLBlock()),
                                ('date', wagtail.blocks.DateBlock()),
                            ]
                        ),
                    ),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    ('html', wagtail.blocks.RawHTMLBlock()),
                    (
                        'subsection',
                        wagtail.blocks.StructBlock(
                            [
                                ('subsection', wagtail.blocks.CharBlock()),
                                ('collapsed', wagtail.blocks.BooleanBlock(default=True, required=False)),
                            ]
                        ),
                    ),
                ],
                null=True,
            ),
        ),
    ]
