# Generated by Django 3.1.14 on 2023-10-15 15:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('dalme_public', '0015_auto_20230813_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='banners',
            field=wagtail.core.fields.StreamField([('banners', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('info', wagtail.core.blocks.TextBlock()), ('page', wagtail.core.blocks.PageChooserBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('start_date', wagtail.core.blocks.DateBlock()), ('end_date', wagtail.core.blocks.DateBlock())]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='sponsors',
            field=wagtail.core.fields.StreamField([('sponsors', wagtail.core.blocks.StructBlock([('logo', wagtail.images.blocks.ImageChooserBlock()), ('url', wagtail.core.blocks.URLBlock())]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))], null=True)),
                ('copyright', models.CharField(blank=True, max_length=255, null=True)),
                ('social', wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('fa_icon', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('css_class', wagtail.core.blocks.CharBlock(required=False))]))], null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
