# Generated by Django 3.1.14 on 2023-10-15 18:10

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('dalme_public', '0016_auto_20231015_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteGradients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=255)),
                ('css_value', models.CharField(help_text='e.g. "59deg, #11587c 54.62%, #1b1b1b".', max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_slug', models.CharField(help_text='A short version of the website\'s name, e.g. "DALME".', max_length=255)),
                ('copyright_owner', models.CharField(help_text="Copyright owner as it should appear on the website's footer.", max_length=255, null=True)),
                ('footer_links', wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))], help_text="Copyright owner as it should appear on the website's footer.", null=True)),
                ('social_media', wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('fa_icon', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('css_class', wagtail.core.blocks.CharBlock(required=False))]))], null=True)),
                ('citation_title', models.CharField(max_length=255, null=True)),
                ('citation_url', models.CharField(max_length=255, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='home',
            name='heading_text',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='show_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
        migrations.AddField(
            model_name='sitegradients',
            name='site',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradients', to='dalme_public.sitesettings'),
        ),
        migrations.AddField(
            model_name='citationauthors',
            name='site',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_authors', to='dalme_public.sitesettings'),
        ),
    ]
