# Generated by Django 3.1.14 on 2023-10-15 18:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0017_auto_20231015_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_links',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))], blank=True, help_text="Copyright owner as it should appear on the website's footer.", null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_media',
            field=wagtail.core.fields.StreamField([('social', wagtail.core.blocks.StructBlock([('fa_icon', wagtail.core.blocks.CharBlock()), ('url', wagtail.core.blocks.URLBlock(required=False)), ('css_class', wagtail.core.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
