# Generated by Django 3.1.14 on 2023-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0018_auto_20231015_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='heading_text',
            field=models.TextField(blank=True, help_text='Heading text to be displayed on top of the heading image (the field accepts HTML).', null=True),
        ),
    ]
