# Generated by Django 3.1.14 on 2023-10-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0019_auto_20231015_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='body_append',
            field=models.TextField(blank=True, help_text='HTML to add after main text body.', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='body_prepend',
            field=models.TextField(blank=True, help_text='HTML to add before main text body.', null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='body_wrapper',
            field=models.CharField(blank=True, help_text='CSS classes for main text body wrapper.', max_length=255, null=True),
        ),
    ]
