# Generated by Django 3.1.14 on 2023-10-15 19:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_public', '0020_auto_20231015_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='body_append',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, help_text='Content to add after main text body.', null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='body_prepend',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True, help_text='Content to add before main text body.', null=True),
        ),
    ]
