# ; -*- mode: dockerfile;-*-
# vim: set ft=dockerfile:
FROM node:20-bookworm-slim AS base
WORKDIR /opt/build
COPY ./ui/package.json ./ui/yarn.lock ./
RUN yarn install --silent

FROM node:20-bookworm-slim AS reqs
WORKDIR /opt/ui
COPY --from=base /opt/build/node_modules ./node_modules
ENV PATH=/opt/ui/node_modules/.bin:$PATH
COPY ./ui .

FROM reqs AS development
CMD ["yarn", "dev"]

FROM reqs AS ci
RUN yarn build

FROM reqs AS production
ARG ENV
ARG BUILD
ARG OAUTH_CLIENT_ID
RUN touch .env.prod
RUN echo VITE_ENV=$ENV >> .env.prod
RUN echo VITE_BUILD=$BUILD >> .env.prod
RUN echo OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID >> .env.prod
RUN cat .env.prod
RUN yarn build
