# ; -*- mode: dockerfile;-*-
# vim: set ft=dockerfile:
FROM nginx:mainline AS serve
COPY . /etc/nginx/
COPY ./config/nginx/production/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
STOPSIGNAL SIGQUIT
