export const columnMap = {
  id: {
    label: "ID",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: true,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
    autoWidth: true,
  },
  status: {
    label: "Status",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  subject: {
    label: "Ticket",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  file: {
    label: "Attachments",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
    autoWidth: true,
  },
  tags: {
    label: "Tags",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  commentCount: {
    label: "Comments",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  creationUser: {
    label: "Created by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  creationTimestamp: {
    label: "Created on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  closingDate: {
    label: "Closed on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
};
