# Generated by Django 4.0.6 on 2022-11-24 15:46

import uuid

import django_currentuser.middleware
import wagtail.search.index

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dalme_app.models.auth_extended
import dalme_app.models.templates


class Migration(migrations.Migration):  # noqa: D101
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='rs_collection',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user', models.IntegerField(null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('public', models.IntegerField(default='0')),
                ('theme', models.CharField(max_length=100, null=True)),
                ('theme2', models.CharField(max_length=100, null=True)),
                ('theme3', models.CharField(max_length=100, null=True)),
                ('allow_changes', models.IntegerField(default='0')),
                ('cant_delete', models.IntegerField(default='0')),
                ('keywords', models.TextField()),
                ('savedsearch', models.IntegerField(null=True)),
                ('home_page_publish', models.IntegerField(null=True)),
                ('home_page_text', models.TextField()),
                ('home_page_image', models.IntegerField(null=True)),
                ('session_id', models.IntegerField(null=True)),
                ('theme4', models.CharField(max_length=100, null=True)),
                ('theme5', models.CharField(max_length=100, null=True)),
                ('theme6', models.CharField(max_length=100, null=True)),
                ('theme7', models.CharField(max_length=100, null=True)),
                ('theme8', models.CharField(max_length=100, null=True)),
                ('theme9', models.CharField(max_length=100, null=True)),
                ('theme10', models.CharField(max_length=100, null=True)),
                ('theme11', models.CharField(max_length=100, null=True)),
                ('theme12', models.CharField(max_length=100, null=True)),
                ('theme13', models.CharField(max_length=100, null=True)),
                ('theme14', models.CharField(max_length=100, null=True)),
                ('theme15', models.CharField(max_length=100, null=True)),
                ('theme16', models.CharField(max_length=100, null=True)),
                ('theme17', models.CharField(max_length=100, null=True)),
                ('theme18', models.CharField(max_length=100, null=True)),
                ('theme19', models.CharField(max_length=100, null=True)),
                ('theme20', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_collection_resource',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(null=True)),
                ('use_as_theme_thumbnail', models.IntegerField(null=True)),
                ('purchase_size', models.CharField(max_length=10, null=True)),
                ('purchase_complete', models.IntegerField(default='0')),
                ('purchase_price', models.FloatField(default='0.00', max_length=10)),
                ('sortorder', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'collection_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('resource_type', models.IntegerField(null=True)),
                ('has_image', models.IntegerField(default='0')),
                ('is_transcoding', models.IntegerField(default='0')),
                ('hit_count', models.IntegerField(default='0')),
                ('new_hit_count', models.IntegerField(default='0')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('user_rating', models.IntegerField(null=True)),
                ('user_rating_count', models.IntegerField(null=True)),
                ('user_rating_total', models.IntegerField(null=True)),
                ('country', models.CharField(default=None, max_length=200, null=True)),
                ('file_extension', models.CharField(max_length=10, null=True)),
                ('preview_extension', models.CharField(max_length=10, null=True)),
                ('image_red', models.IntegerField(null=True)),
                ('image_green', models.IntegerField(null=True)),
                ('image_blue', models.IntegerField(null=True)),
                ('thumb_width', models.IntegerField(null=True)),
                ('thumb_height', models.IntegerField(null=True)),
                ('archive', models.IntegerField(default='0')),
                ('access', models.IntegerField(default='0')),
                ('colour_key', models.CharField(max_length=5, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('file_path', models.CharField(max_length=500, null=True)),
                ('file_modified', models.DateTimeField(blank=True, null=True)),
                ('file_checksum', models.CharField(max_length=32, null=True)),
                ('request_count', models.IntegerField(default='0')),
                ('expiry_notification_sent', models.IntegerField(default='0')),
                ('preview_tweaks', models.CharField(max_length=50, null=True)),
                ('geo_lat', models.FloatField(default=None, null=True)),
                ('geo_long', models.FloatField(default=None, null=True)),
                ('mapzoom', models.IntegerField(null=True)),
                ('disk_usage', models.IntegerField(null=True)),
                ('disk_usage_last_updated', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=None, null=True)),
                ('preview_attempts', models.IntegerField(default=None, null=True)),
                ('field12', models.CharField(default=None, max_length=200, null=True)),
                ('field8', models.CharField(default=None, max_length=200, null=True)),
                ('field3', models.CharField(default=None, max_length=200, null=True)),
                ('annotation_count', models.IntegerField(null=True)),
                ('field51', models.CharField(default=None, max_length=200, null=True)),
                ('field79', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource_data',
            fields=[
                ('django_id', models.IntegerField(db_column='django_id', primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'resource_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource_type_field',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=400, null=True)),
                ('type', models.IntegerField(null=True)),
                ('order_by', models.IntegerField(default='0')),
                ('keywords_index', models.IntegerField(default='0')),
                ('partial_index', models.IntegerField(default='0')),
                ('resource_type', models.IntegerField(default='0')),
                ('resource_column', models.CharField(max_length=50, null=True)),
                ('display_field', models.IntegerField(default='1')),
                ('use_for_similar', models.IntegerField(default='1')),
                ('iptc_equiv', models.CharField(max_length=20, null=True)),
                ('display_template', models.TextField()),
                ('tab_name', models.CharField(max_length=50, null=True)),
                ('required', models.IntegerField(default='0')),
                ('smart_theme_name', models.CharField(max_length=200, null=True)),
                ('exiftool_field', models.CharField(max_length=200, null=True)),
                ('advanced_search', models.IntegerField(default='1')),
                ('simple_search', models.IntegerField(default='0')),
                ('help_text', models.TextField()),
                ('display_as_dropdown', models.IntegerField(default='0')),
                ('external_user_access', models.IntegerField(default='1')),
                ('autocomplete_macro', models.TextField()),
                ('hide_when_uploading', models.IntegerField(default='0')),
                ('hide_when_restricted', models.IntegerField(default='0')),
                ('value_filter', models.TextField()),
                ('exiftool_filter', models.TextField()),
                ('omit_when_copying', models.IntegerField(default='0')),
                ('tooltip_text', models.TextField()),
                ('regexp_filter', models.CharField(max_length=400, null=True)),
                ('sync_field', models.IntegerField(null=True)),
                ('display_condition', models.CharField(max_length=400, null=True)),
                ('onchange_macro', models.TextField()),
                ('field_constraint', models.IntegerField(null=True)),
                ('linked_data_field', models.TextField()),
                ('automatic_nodes_ordering', models.IntegerField(default='0')),
                ('fits_field', models.CharField(max_length=255, null=True)),
                ('personal_data', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'resource_type_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_user',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                (
                    'usergroup',
                    models.IntegerField(
                        choices=[(2, 'General User'), (4, 'Archivist'), (1, 'Administrator'), (3, 'Super Admin')],
                        null=True,
                    ),
                ),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('logged_in', models.IntegerField(null=True)),
                ('last_browser', models.TextField()),
                ('last_ip', models.CharField(max_length=100, null=True)),
                ('current_collection', models.IntegerField(null=True)),
                ('accepted_terms', models.IntegerField(default='0')),
                ('account_expires', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('session', models.CharField(max_length=50, null=True)),
                ('ip_restrict', models.TextField()),
                ('search_filter_override', models.TextField()),
                ('password_last_change', models.DateTimeField(null=True)),
                ('login_tries', models.IntegerField(default='0')),
                ('login_last_try', models.DateTimeField(blank=True, null=True)),
                ('approved', models.IntegerField(default='1')),
                ('lang', models.CharField(max_length=11, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hidden_collections', models.TextField()),
                ('password_reset_hash', models.CharField(max_length=100, null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('unique_hash', models.CharField(max_length=50, null=True)),
                ('wp_authrequest', models.CharField(max_length=50, null=True)),
                ('csrf_token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('standard_name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Person'), (2, 'Organization')])),
                ('notes', models.TextField(blank=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='agent',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('type', models.CharField(max_length=255, null=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_related',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute_type',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField()),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('DATE', 'DATE (date)'),
                            ('DEC', 'DEC (decimal)'),
                            ('INT', 'INT (integer)'),
                            ('STR', 'STR (string)'),
                            ('TXT', 'TXT (text)'),
                            ('FK-UUID', 'FK-UUID (DALME record)'),
                            ('FK-INT', 'FK-INT (DALME record)'),
                        ],
                        max_length=15,
                    ),
                ),
                ('source', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('options_list', models.CharField(blank=True, default=None, max_length=255, null=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'same_as',
                    models.ForeignKey(
                        db_column='same_as',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.attribute_type',
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('getty_id', models.IntegerField(db_index=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content_attributes',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.IntegerField(db_index=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=True)),
                (
                    'attribute_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='content_types',
                        to='dalme_app.attribute_type',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Content_class',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField()),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content_type',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('has_pages', models.BooleanField(db_index=True, default=False)),
                ('has_inventory', models.BooleanField(default=False)),
                ('parents', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('r1_inheritance', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('r2_inheritance', models.CharField(blank=True, default=None, max_length=255, null=True)),
                (
                    'attribute_types',
                    models.ManyToManyField(through='dalme_app.Content_attributes', to='dalme_app.attribute_type'),
                ),
                (
                    'content_class',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.content_class'),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CountryReference',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('num_code', models.IntegerField()),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entity_phrase',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(db_index=True, null=True)),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Headword',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('word', models.CharField(max_length=55)),
                ('full_lemma', models.CharField(max_length=255)),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.concept')),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocaleReference',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('administrative_region', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.countryreference',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['country', 'name'],
                'unique_together': {('name', 'administrative_region')},
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.concept')),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=55)),
                ('dam_id', models.IntegerField(db_index=True, null=True)),
                ('order', models.IntegerField(db_index=True)),
                ('canvas', models.TextField(null=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'set_type',
                    models.IntegerField(choices=[(1, 'Corpus'), (2, 'Collection'), (3, 'Dataset'), (4, 'Workset')]),
                ),
                ('is_public', models.BooleanField(default=False)),
                ('has_landing', models.BooleanField(default=False)),
                ('endpoint', models.CharField(max_length=55)),
                (
                    'permissions',
                    models.IntegerField(
                        choices=[
                            (1, 'Private'),
                            (2, 'Others: view'),
                            (3, 'Others: view|add'),
                            (4, 'Others: view|add|delete'),
                        ],
                        default=2,
                    ),
                ),
                ('description', models.TextField()),
                ('stat_title', models.CharField(blank=True, max_length=25, null=True)),
                ('stat_text', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'dataset_usergroup',
                    models.ForeignKey(
                        limit_choices_to={'properties__type': 3},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dataset',
                        to='auth.group',
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_related',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
                ('has_inventory', models.BooleanField(db_index=True, default=False)),
                ('is_private', models.BooleanField(db_index=True, default=False)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_related',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Wordform',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('normalized_form', models.CharField(max_length=55)),
                ('pos', models.CharField(max_length=255)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'headword_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.headword'),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('transcription', models.TextField(blank=True, default=None)),
                ('author', models.CharField(default=dalme_app.models.templates.get_current_username, max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('count_ignore', models.BooleanField(default=False)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('raw_token', models.CharField(max_length=255)),
                ('clean_token', models.CharField(max_length=55)),
                ('order', models.IntegerField(db_index=True)),
                ('flags', models.CharField(max_length=10)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'object_phrase_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.entity_phrase'),
                ),
                (
                    'wordform_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.wordform'),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('subject', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                (
                    'assigned_to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ticket_assigned_to',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'closing_user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'file',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.attachment',
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['status', 'creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(default='')),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'group',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_list_group',
                        to='auth.group',
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_related',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name_plural': 'Task Lists',
                'ordering': ['name'],
                'unique_together': {('group', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, default=None, max_length=255)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                (
                    'assigned_to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_assigned_to',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='task_created_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'file',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.attachment',
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.tasklist')),
                (
                    'workset',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.set'),
                ),
            ],
            options={
                'ordering': ['priority', 'creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Source_pages',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sources',
                        to='dalme_app.page',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='source_pages',
                        to='dalme_app.source',
                    ),
                ),
                (
                    'transcription',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='source_pages',
                        to='dalme_app.transcription',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='source',
            name='pages',
            field=models.ManyToManyField(db_index=True, through='dalme_app.Source_pages', to='dalme_app.page'),
        ),
        migrations.AddField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='children',
                to='dalme_app.source',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='primary_dataset',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_query_name='set_members',
                to='dalme_app.set',
            ),
        ),
        migrations.AddField(
            model_name='source',
            name='type',
            field=models.ForeignKey(
                db_column='type',
                on_delete=django.db.models.deletion.PROTECT,
                to='dalme_app.content_type',
            ),
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                (
                    'type',
                    models.IntegerField(choices=[(1, 'Temporal'), (2, 'Spatial'), (3, 'Linguistic'), (4, 'Context')]),
                ),
                ('range', models.TextField()),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('search', models.JSONField()),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_related',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightsPolicy',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                (
                    'rights_status',
                    models.IntegerField(
                        choices=[
                            (1, 'Copyrighted'),
                            (2, 'Orphaned'),
                            (3, 'Owned'),
                            (4, 'Public Domain'),
                            (5, 'Unknown'),
                        ],
                        default=5,
                    ),
                ),
                ('rights', models.TextField(blank=True, default=None)),
                ('rights_notice', models.JSONField(null=True)),
                ('licence', models.TextField(blank=True, default=None, null=True)),
                ('rights_holder', models.CharField(default=None, max_length=255, null=True)),
                ('notice_display', models.BooleanField(default=False)),
                ('public_display', models.BooleanField(default=True)),
                (
                    'attachments',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.attachment',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('source_object_id', models.UUIDField(db_index=True, null=True)),
                ('target_object_id', models.UUIDField(db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'scope',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.scope'),
                ),
                (
                    'source_content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relationship_sources',
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'target_content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='relationship_targets',
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicRegister',
            fields=[
                ('object_id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('preferences', models.JSONField(default=dalme_app.models.auth_extended.default_preferences)),
                (
                    'primary_group',
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('standard_name', models.CharField(max_length=255)),
                ('type', models.IntegerField(db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'locale',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.localereference',
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Object_attribute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                (
                    'attribute_concept',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.concept'),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.object')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageReference',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('glottocode', models.CharField(max_length=25, unique=True)),
                ('iso6393', models.CharField(blank=True, default=None, max_length=25, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'Language'), (2, 'Dialect')])),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'parent',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dalme_app.languagereference',
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'type',
                    models.IntegerField(
                        choices=[(1, 'Admin'), (2, 'DAM'), (3, 'Dataset'), (4, 'Knowledge Base'), (5, 'Website')],
                    ),
                ),
                ('description', models.CharField(max_length=255)),
                (
                    'group',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='properties',
                        to='auth.group',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='entity_phrase',
            name='transcription_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='entity_phrases',
                to='dalme_app.transcription',
            ),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='content_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attribute_type_list',
                to='dalme_app.content_type',
            ),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='creation_user',
            field=models.ForeignKey(
                default=django_currentuser.middleware.get_current_user,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_creation',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='modification_user',
            field=models.ForeignKey(
                default=django_currentuser.middleware.get_current_user,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%(app_label)s_%(class)s_modification',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.CharField(db_index=True, max_length=55, null=True)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttributeReference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('data_type', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=255)),
                ('term_type', models.CharField(blank=True, default=None, max_length=55)),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                (
                    'source',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='workflow',
                        serialize=False,
                        to='dalme_app.source',
                    ),
                ),
                (
                    'wf_status',
                    models.IntegerField(choices=[(1, 'assessing'), (2, 'processing'), (3, 'processed')], default=2),
                ),
                (
                    'stage',
                    models.IntegerField(
                        choices=[(1, 'ingestion'), (2, 'transcription'), (3, 'markup'), (4, 'review'), (5, 'parsing')],
                        default=1,
                    ),
                ),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('help_flag', models.BooleanField(default=False)),
                ('ingestion_done', models.BooleanField(default=False)),
                ('transcription_done', models.BooleanField(default=False)),
                ('markup_done', models.BooleanField(default=False)),
                ('parsing_done', models.BooleanField(default=False)),
                ('review_done', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                (
                    'last_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Work_log',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('event', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='work_log',
                        to='dalme_app.workflow',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                (
                    'tag_type',
                    models.CharField(choices=[('WF', 'Workflow'), ('C', 'Control'), ('T', 'Ticket')], max_length=2),
                ),
                ('tag', models.CharField(default=None, max_length=55, null=True)),
                ('tag_group', models.CharField(default=None, max_length=255, null=True)),
                ('object_id', models.CharField(db_index=True, max_length=55, null=True)),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('tag', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Source_credit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Editor'), (2, 'Corrections'), (3, 'Contributor')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credits',
                        to='dalme_app.agent',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='credits',
                        to='dalme_app.source',
                    ),
                ),
            ],
            options={
                'unique_together': {('source', 'agent', 'type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('type', 'name')},
        ),
        migrations.CreateModel(
            name='Set_x_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('workset_done', models.BooleanField(default=False)),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'set_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='dalme_app.set',
                    ),
                ),
            ],
            options={
                'ordering': ['set_id', 'id'],
                'unique_together': {('content_type', 'object_id', 'set_id')},
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('object_id', models.UUIDField(db_index=True, null=True)),
                ('value_STR', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('value_DATE_d', models.IntegerField(blank=True, null=True)),
                ('value_DATE_m', models.IntegerField(blank=True, null=True)),
                ('value_DATE_y', models.IntegerField(blank=True, null=True)),
                ('value_DATE', models.DateField(blank=True, null=True)),
                ('value_INT', models.IntegerField(blank=True, null=True)),
                ('value_DEC', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('value_TXT', models.TextField(blank=True, default=None, null=True)),
                ('value_JSON', models.JSONField(null=True)),
                (
                    'attribute_type',
                    models.ForeignKey(
                        db_column='attribute_type',
                        on_delete=django.db.models.deletion.CASCADE,
                        to='dalme_app.attribute_type',
                    ),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
                (
                    'creation_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'modification_user',
                    models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('object_id', 'attribute_type', 'value_STR')},
            },
        ),
    ]
