# Generated by Django 2.0.5 on 2018-06-18 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # Squashed several intermediate migrations before commit
    # replaces = [('dalme_app', '0002_auto_20180618_1455'), ('dalme_app', '0003_auto_20180618_1512'), ('dalme_app', '0004_auto_20180618_1532'), ('dalme_app', '0005_auto_20180618_1552')]

    dependencies = [
        ('dalme_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_date',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_DATE', to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_dbr',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_DBR', to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_int',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_INT', to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_str',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_STR', to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_txt',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_TXT', to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Content_type'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Source'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Attribute_type'),
        ),
        migrations.AlterField(
            model_name='attribute_date',
            name='attribute_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_dbr',
            name='attribute_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_int',
            name='attribute_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_str',
            name='attribute_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute'),
        ),
        migrations.AlterField(
            model_name='attribute_txt',
            name='attribute_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute'),
        ),
    ]
