# Generated by Django 4.2.2 on 2024-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
