# Generated by Django 4.2.1 on 2023-06-12 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0004_model_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeValueBool',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueDate',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                (
                    'day',
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    'month',
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ('year', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('text', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueDec',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueInt',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueJson',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueStr',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.CreateModel(
            name='AttributeValueTxt',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='object_id',
            field=models.CharField(db_index=True, default='', max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_STR',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_TXT',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='data_type',
            field=models.CharField(
                choices=[
                    ('BOOL', 'BOOL (boolean)'),
                    ('DATE', 'DATE (date)'),
                    ('DEC', 'DEC (decimal)'),
                    ('FKEY', 'FKEY (foreign key)'),
                    ('INT', 'INT (integer)'),
                    ('JSON', 'JSON (data)'),
                    ('STR', 'STR (string)'),
                    ('TXT', 'TXT (text)'),
                    ('FK-UUID', 'FK-UUID (DALME record)'),
                    ('FK-INT', 'FK-INT (DALME record)'),
                ],
                max_length=15,
            ),
        ),
        migrations.RemoveField(
            model_name='attributetype',
            name='options_list',
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attributetype',
            name='options',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='dalme_app.optionslist',
            ),
        ),
        migrations.AddField(
            model_name='contentattributetypes',
            name='options_override',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='dalme_app.optionslist',
            ),
        ),
        migrations.CreateModel(
            name='AttributeValueFkey',
            fields=[
                (
                    'attribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='dalme_app.attribute',
                    ),
                ),
                ('target_id', models.CharField(db_index=True, max_length=36)),
                (
                    'target_content_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fk_attributes',
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('dalme_app.attribute',),
        ),
        # the next two commands are necessary because when migrating from MySQL to Postgres
        # certain constrints were created as indices and Postgres doesn't look for indices
        # when altering constraints, so we drop the index and recreate it as a constraint proper
        migrations.RunSQL("DROP INDEX idx_16430_dalme_app_attribute_object_id_attribute_type_c83849ec;"),
        migrations.RunSQL(
            'ALTER TABLE public.dalme_app_attribute ADD CONSTRAINT idx_16430_dalme_app_attribute_object_id_attribute_type_c83849ec UNIQUE(object_id, attribute_type, "value_STR");',
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(
                db_column='attribute_type',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attributes',
                to='dalme_app.attributetype',
            ),
        ),
    ]
