# Generated by Django 2.0.5 on 2018-07-25 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dalme_app', '0005_page_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
