# Generated by Django 3.1.2 on 2021-02-20 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_closing(apps, schema_editor):
    TicketModel = apps.get_model('dalme_app', 'Ticket')
    tickets = TicketModel.objects.filter(status=1)
    for ticket in tickets:
        ticket.closing_date = ticket.modification_timestamp
        ticket.closing_user = ticket.modification_user
        ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0005_auto_20210217_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(assign_closing, migrations.RunPython.noop),
    ]
