# Generated by Django 2.1.7 on 2019-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0006_auto_20180725_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_type',
            name='default_headers',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
