# Generated by Django 3.1.14 on 2023-10-22 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0006_auto_20210220_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryReference',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('zotero_id', models.IntegerField()),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('editions_id', models.CharField(max_length=55)),
                ('creation_user', models.ForeignKey(default=django_currentuser.middleware.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_libraryreference_creation', to=settings.AUTH_USER_MODEL)),
                ('modification_user', models.ForeignKey(default=django_currentuser.middleware.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_libraryreference_modification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
