# Generated by Django 2.1.7 on 2019-02-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0009_content_list_extra_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_date',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
