# Generated by Django 2.1.7 on 2019-03-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0010_attribute_date_value_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.IntegerField(db_index=True, unique=True)),
                ('level', models.IntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (25, 'SUCCESS'), (30, 'WARNING'), (40, 'ERROR')])),
                ('type', models.IntegerField(choices=[(1, 'MODAL'), (2, 'NOTIFICATION')])),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
