# Generated by Django 2.1.7 on 2019-03-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0011_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Word_form',
            new_name='Wordform',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='word_form_id',
            new_name='wordform_id',
        ),
    ]
