# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-04 21:06
from __future__ import unicode_literals

import dalme_app.modelTemplates
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0011_auto_20170707_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='par_folios',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('folio_no', models.CharField(max_length=32)),
                ('dam_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='par_inventories',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=16)),
                ('shelf', models.CharField(max_length=32)),
                ('transcriber', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='par_tokens',
            fields=[
                ('_id', models.CharField(db_column='id', default=dalme_app.modelTemplates.make_uuid, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('line_no', models.IntegerField()),
                ('position', models.IntegerField()),
                ('raw_token', models.CharField(max_length=64)),
                ('clean_token', models.CharField(max_length=64)),
                ('norm_token', models.CharField(max_length=64)),
                ('token_type', models.CharField(max_length=32)),
                ('flags', models.CharField(max_length=16)),
                ('span_start', models.IntegerField()),
                ('folio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.par_folios')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='par_folios',
            name='inv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.par_inventories'),
        ),
    ]
