# Generated by Django 2.1.7 on 2019-03-09 15:44

import dalme_app.middleware
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0012_auto_20190302_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='error_message',
        ),
        migrations.AddField(
            model_name='profile',
            name='wp_avatar_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_date',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_date',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_dbr',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_dbr',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_int',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_int',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_str',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_str',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_txt',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_txt',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_class',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_class',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_list',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_list',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_list_x_content_type',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_list_x_content_type',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_type',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_type',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_type_x_attribute_type',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_type_x_attribute_type',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headword',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='headword',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identity_phrase',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identity_phrase',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identity_phrase_x_entity',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identity_phrase_x_entity',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object_attribute',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object_attribute',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object_phrase',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object_phrase',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_folio',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_folio',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_inventory',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_inventory',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_token',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='par_token',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordform',
            name='creation_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordform',
            name='modification_username',
            field=models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True),
        ),
    ]
