# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-05 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0012_auto_20170804_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='par_tokens',
            name='span_end',
            field=models.IntegerField(default='d'),
            preserve_default=False,
        ),
    ]
