# Generated by Django 4.2.2 on 2023-06-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    dependencies = [
        ('dalme_app', '0012_data_m_local_values'),
    ]

    operations = [
        # the next two commands are necessary because when migrating from MySQL to Postgres
        # certain constrints were created as indices and Postgres doesn't look for indices
        # when altering constraints, so we drop the index and recreate it as a constraint proper
        migrations.RunSQL("DROP INDEX idx_16554_dalme_app_set_x_content_content_type_id_object_i_8838;"),
        migrations.RunSQL(
            'ALTER TABLE public.dalme_app_set_x_content ADD CONSTRAINT idx_16554_dalme_app_set_x_content_content_type_id_object_i_8838 UNIQUE(content_type_id, object_id, set_id_id);',
        ),
        migrations.AlterUniqueTogether(
            name='set_x_content',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='modification_user',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='set_id',
        ),
        migrations.RemoveField(
            model_name='contenttypeextended',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workset',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_d',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_m',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_y',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DEC',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_INT',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_JSON',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_STR',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_TXT',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_group',
        ),
        migrations.RemoveField(
            model_name='source',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='source',
            name='primary_dataset',
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='data_type',
            field=models.CharField(
                choices=[
                    ('BOOL', 'BOOL (boolean)'),
                    ('DATE', 'DATE (date)'),
                    ('DEC', 'DEC (decimal)'),
                    ('FKEY', 'FKEY (foreign key)'),
                    ('INT', 'INT (integer)'),
                    ('JSON', 'JSON (data)'),
                    ('RREL', 'RREL (reverse relation)'),
                    ('STR', 'STR (string)'),
                    ('TXT', 'TXT (text)'),
                ],
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Set_x_content',
        ),
        migrations.DeleteModel(
            name='SourceCredits',
        ),
        migrations.RenameField(
            model_name='contenttypeextended',
            old_name='parents_list',
            new_name='parents',
        ),
        migrations.RemoveField(
            model_name='contenttypeextended',
            name='has_inventory',
        ),
        migrations.RemoveField(
            model_name='contenttypeextended',
            name='has_pages',
        ),
    ]
