# Generated by Django 4.2.2 on 2023-06-14 14:28
from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101
    atomic = False
    dependencies = [
        ('dalme_app', '0013_data_m_local_values'),
    ]

    operations = [
        # Agent
        migrations.RemoveField(
            model_name='agent',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='old_user',
        ),
        # Attribute
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_d',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_m',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DATE_y',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_DEC',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_INT',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_JSON',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_STR',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='value_TXT',
        ),
        # AttributeType
        migrations.RemoveField(
            model_name='attributetype',
            name='options_list',
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='data_type',
            field=models.CharField(
                choices=[
                    ('BOOL', 'BOOL (boolean)'),
                    ('DATE', 'DATE (date)'),
                    ('DEC', 'DEC (decimal)'),
                    ('FKEY', 'FKEY (foreign key)'),
                    ('INT', 'INT (integer)'),
                    ('JSON', 'JSON (data)'),
                    ('RREL', 'RREL (reverse relation)'),
                    ('STR', 'STR (string)'),
                    ('TXT', 'TXT (text)'),
                ],
                max_length=15,
            ),
        ),
        # Place
        migrations.RemoveField(
            model_name='place',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='place',
            name='type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='locale',
        ),
        # Profile
        migrations.RemoveField(
            model_name='profile',
            name='primary_group',
        ),
        # Source/Record
        migrations.RemoveField(
            model_name='record',
            name='old_parent',
        ),
        migrations.RemoveField(
            model_name='record',
            name='primary_dataset',
        ),
        migrations.RemoveField(
            model_name='record',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='record',
            name='has_inventory',
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together=set(),
        ),
        # Scope
        migrations.RemoveField(
            model_name='scope',
            name='scope_range',
        ),
        # Task
        migrations.RemoveField(
            model_name='task',
            name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workset',
        ),
        # REMOVE RELATED FIELDS FROM MODELS TO BE DELETED
        # Content_type
        migrations.RemoveField(
            model_name='content_type',
            name='attribute_types',
        ),
        migrations.RemoveField(
            model_name='content_type',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='content_type',
            name='modification_user',
        ),
        migrations.RemoveField(
            model_name='content_type',
            name='parents',
        ),
        # Set
        migrations.RemoveField(
            model_name='set',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='dataset_usergroup',
        ),
        migrations.RemoveField(
            model_name='set',
            name='modification_user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='owner',
        ),
        # set_x_content
        migrations.AlterUniqueTogether(
            name='set_x_content',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='modification_user',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='set_id',
        ),
        # Record
        migrations.RemoveField(
            model_name='record',
            name='type',
        ),
        #  SourceCredits
        migrations.AlterUniqueTogether(
            name='sourcecredits',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sourcecredits',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='sourcecredits',
            name='creation_user',
        ),
        migrations.RemoveField(
            model_name='sourcecredits',
            name='modification_user',
        ),
        migrations.RemoveField(
            model_name='sourcecredits',
            name='source',
        ),
        # DELETE MODELS
        migrations.DeleteModel(
            name='Content_attributes',
        ),
        migrations.DeleteModel(
            name='Content_type',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='Set_x_content',
        ),
        migrations.DeleteModel(
            name='SourceCredits',
        ),
        migrations.RemoveField(
            model_name='languagereference',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='file',
        ),
        migrations.DeleteModel(
            name='Content_class',
        ),
    ]
