# Generated by Django 2.1.7 on 2019-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0013_auto_20190309_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_list',
            name='content_types',
            field=models.ManyToManyField(to='dalme_app.Content_type'),
        ),
    ]
