# Generated by Django 2.1.7 on 2019-03-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0014_content_list_content_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_list_x_content_type',
            name='content_list',
        ),
        migrations.RemoveField(
            model_name='content_list_x_content_type',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Content_list_x_content_type',
        ),
    ]
