# Generated by Django 2.1.7 on 2019-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0016_auto_20190315_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='content_id',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='object_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
