# Generated by Django 2.1.7 on 2019-03-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0017_auto_20190315_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value_DATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_DATE_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_DATE_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_DATE_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_DBR',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_INT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_STR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='value_TXT',
            field=models.TextField(blank=True, null=True),
        ),
    ]
