# Generated by Django 4.2.2 on 2024-02-15 15:29
from django.db import migrations

# The existing data has been synchronized between all the schemas at some point
# automatically during the migrations process. So in this data migration we
# need to clean that up. For the given set of 'tenant' tables, only the 'dalme'
# schema should have any data at all in it (at this point).
#
# Here then, we need to truncate to empty all the relevant tables
# (specifically, the union of tables found between a tenant schema and the
# 'public' schema) across all the relevant schemas.
#
# We can also drop the remnant 'wagtailsearch_editorspick' from the 'public
# schema altogether as it's now fully deprecated and remains only as noise.

CLEAN_SCHEMAS = """
BEGIN;

DO $$
  DECLARE
  tb text;
BEGIN
  FOR tb IN
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    AND table_name IN
    (SELECT table_name FROM information_schema.tables WHERE table_schema = 'globalpharmacopeias')
    AND table_name <> 'wagtailcore_pagerevision'  -- This is redundant but it's clarifying.
    AND table_name <> 'django_migrations'
    LOOP

    -- Truncate the existing table in both schemas
    EXECUTE format('TRUNCATE TABLE public.%I CASCADE;', tb);
    EXECUTE format('TRUNCATE TABLE globalpharmacopeias.%I CASCADE;', tb);

  END LOOP;

  -- Delete remnant editor's pick table.
  DROP TABLE public.wagtailsearch_editorspick CASCADE;

END $$;
COMMIT;
"""


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0017_auto_20240215_1029'),
        ('dalme_app', '0016_attachment_tenant_collection_tenant_and_more'),
    ]

    operations = [
        migrations.RunSQL(CLEAN_SCHEMAS),
    ]
