# Generated by Django 4.2.2 on 2023-12-13 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0017_alter_profile_preferences'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Profile',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Profile',
                    table='ida_profile',
                ),
            ],
        )
    ]
