# Generated by Django 4.2.2 on 2023-12-13 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0018_delete_profile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='GroupProperties',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='GroupProperties',
                    table='ida_groupproperties',
                ),
            ],
        )
    ]
