# Generated by Django 2.1.7 on 2019-03-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0018_auto_20190315_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute_date',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='attribute_dbr',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='attribute_int',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='attribute_str',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='attribute_txt',
            name='attribute_id',
        ),
        migrations.AlterModelOptions(
            name='attribute_type',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='content_class',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='content_list',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='content_type',
            options={'ordering': ['id']},
        ),
        migrations.DeleteModel(
            name='Attribute_DATE',
        ),
        migrations.DeleteModel(
            name='Attribute_DBR',
        ),
        migrations.DeleteModel(
            name='Attribute_INT',
        ),
        migrations.DeleteModel(
            name='Attribute_STR',
        ),
        migrations.DeleteModel(
            name='Attribute_TXT',
        ),
    ]
