# Generated by Django 4.2.2 on 2023-12-13 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0019_delete_groupproperties'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='organization',
                    name='agent_ptr',
                ),
                migrations.RemoveField(
                    model_name='organization',
                    name='location',
                ),
                migrations.RemoveField(
                    model_name='person',
                    name='agent_ptr',
                ),
                migrations.RemoveField(
                    model_name='person',
                    name='user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Agent',
                ),
                migrations.DeleteModel(
                    name='Organization',
                ),
                migrations.DeleteModel(
                    name='Person',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Agent',
                    table='ida_agent',
                ),
                migrations.AlterModelTable(
                    name='Organization',
                    table='ida_organization',
                ),
                migrations.AlterModelTable(
                    name='Person',
                    table='ida_person',
                ),
            ],
        ),
    ]
