# Generated by Django 2.1.7 on 2019-03-16 17:56

import dalme_app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0019_auto_20190316_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_pages',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.model_templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.model_templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.IntegerField(db_index=True)),
                ('transcription', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='sources',
        ),
        migrations.AddField(
            model_name='source_pages',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Page'),
        ),
        migrations.AddField(
            model_name='source_pages',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Source'),
        ),
        migrations.AddField(
            model_name='source',
            name='pages',
            field=models.ManyToManyField(db_index=True, through='dalme_app.Source_pages', to='dalme_app.Page'),
        ),
    ]
