# Generated by Django 2.1.7 on 2019-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0020_auto_20190316_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_pages',
            name='order',
        ),
    ]
