# Generated by Django 4.2.2 on 2023-12-13 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0008_concept'),
        ('dalme_app', '0020_remove_organization_agent_ptr_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Concept',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Concept',
                    table='ida_concept',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='headword',
                    name='concept_id',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida.concept'),
                ),
                migrations.AlterField(
                    model_name='object',
                    name='concept',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ida.concept'),
                ),
                migrations.AlterField(
                    model_name='objectattribute',
                    name='attribute_concept',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ida.concept'),
                ),
            ],
            database_operations=[],
        ),
    ]
