# Generated by Django 2.1.7 on 2019-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0021_remove_source_pages_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_pages',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
