# Generated by Django 4.2.2 on 2023-12-13 17:39
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0010_wordform'),
        ('dalme_app', '0022_alter_wordform_headword_id_delete_headword'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Wordform',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Wordform',
                    table='ida_wordform',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='token',
                    name='wordform_id',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ida.wordform'),
                ),
            ],
            database_operations=[],
        ),
    ]
