# Generated by Django 2.1.7 on 2019-03-22 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0022_auto_20190316_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_pages',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='source_id',
        ),
        migrations.AddField(
            model_name='source_pages',
            name='transcription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Transcription'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
