# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-06 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0023_auto_20170805_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='error_messages',
            fields=[
                ('_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('_level', models.IntegerField(choices=[('10', 'DEBUG'), ('20', 'INFO'), ('25', 'SUCCESS'), ('30', 'WARNING'), ('40', 'ERROR')])),
                ('_text', models.CharField(max_length=255)),
                ('_type', models.IntegerField(choices=[('1', 'MODAL'), ('2', 'NOTIFICATION')])),
            ],
        ),
    ]
