# Generated by Django 4.2.2 on 2023-12-13 17:49
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0011_transcription'),
        ('dalme_app', '0023_alter_token_wordform_id_delete_wordform'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Transcription',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Transcription',
                    table='ida_transcription',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='entityphrase',
                    name='transcription_id',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='entity_phrases',
                        to='ida.transcription',
                    ),
                ),
                migrations.AlterField(
                    model_name='folio',
                    name='transcription',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='folios',
                        to='ida.transcription',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
