# Generated by Django 4.2.2 on 2023-12-13 17:57
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0024_alter_entityphrase_transcription_id_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Token',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Token',
                    table='ida_token',
                ),
            ],
        )
    ]
