# Generated by Django 2.1.7 on 2019-03-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0024_attributereference'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributereference',
            name='term_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
