# Generated by Django 2.1.7 on 2019-03-23 15:07

import dalme_app.middleware
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0025_attributereference_term_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.middleware.get_current_user, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.middleware.get_current_user, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('target', models.UUIDField(db_index=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transcription',
            name='author',
            field=models.CharField(default=dalme_app.middleware.get_current_user, max_length=255),
        ),
    ]
