# Generated by Django 4.2.2 on 2023-12-13 18:06
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0025_delete_token'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Ticket',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Ticket',
                    table='ida_ticket',
                ),
            ],
        )
    ]
