# Generated by Django 2.1.7 on 2019-03-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0026_auto_20190323_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='dam_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
