# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0026_auto_20170806_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error_messages',
            name='e_level',
            field=models.IntegerField(choices=[(10, 'DEBUG'), (20, 'INFO'), (25, 'SUCCESS'), (30, 'WARNING'), (40, 'ERROR')]),
        ),
        migrations.AlterField(
            model_name='error_messages',
            name='e_type',
            field=models.IntegerField(choices=[(1, 'MODAL'), (2, 'NOTIFICATION')]),
        ),
    ]
