# Generated by Django 4.2.2 on 2023-12-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0014_scopetype_scope'),
        ('dalme_app', '0026_delete_ticket'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='scopetype',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='scopetype',
                    name='modification_user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Scope',
                ),
                migrations.DeleteModel(
                    name='ScopeType',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Scope',
                    table='ida_scope',
                ),
                migrations.AlterModelTable(
                    name='ScopeType',
                    table='ida_scopetype',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='relationship',
                    name='scopes',
                    field=models.ManyToManyField(db_index=True, to='ida.scope'),
                ),
            ],
            database_operations=[],
        ),
    ]
