# Generated by Django 4.2.2 on 2023-12-13 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0027_remove_scopetype_creation_user_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='RightsPolicy',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='RightsPolicy',
                    table='ida_rightspolicy',
                ),
            ],
        ),
    ]
