# Generated by Django 4.2.2 on 2023-12-13 18:29
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0028_delete_rightspolicy'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='relationshiptype',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='relationshiptype',
                    name='modification_user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Relationship',
                ),
                migrations.DeleteModel(
                    name='RelationshipType',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Relationship',
                    table='ida_relationship',
                ),
                migrations.AlterModelTable(
                    name='RelationshipType',
                    table='ida_relationshiptype',
                ),
            ],
        ),
    ]
