# Generated by Django 2.1.7 on 2019-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0030_profile_wp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dam_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wiki_user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wp_user',
            field=models.IntegerField(null=True),
        ),
    ]
