# Generated by Django 4.2.2 on 2023-12-14 10:52
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0031_delete_place'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PublicRegister',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='PublicRegister',
                    table='ida_publicregister',
                ),
            ],
        ),
    ]
