# Generated by Django 2.1.7 on 2019-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0032_auto_20190419_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt_list',
            name='api_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='form_helper',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
