# Generated by Django 2.1.7 on 2019-04-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0033_auto_20190419_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_type',
            name='same_as',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
