# Generated by Django 4.2.2 on 2023-12-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0021_page'),
        ('dalme_app', '0033_delete_permission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='folio',
                    name='page',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ida.page'
                    ),
                ),
                migrations.AlterField(
                    model_name='record',
                    name='pages',
                    field=models.ManyToManyField(db_index=True, through='dalme_app.Folio', to='ida.page'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Page',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Page',
                    table='ida_page',
                ),
            ],
        ),
    ]
