# Generated by Django 4.2.2 on 2023-12-16 12:30
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0022_optionslist'),
        ('dalme_app', '0034_alter_folio_page_alter_record_pages_delete_page'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attributetype',
                    name='options',
                    field=models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.optionslist'
                    ),
                ),
                migrations.AlterField(
                    model_name='contentattributes',
                    name='override_options',
                    field=models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.optionslist'
                    ),
                ),
                migrations.DeleteModel(
                    name='OptionsList',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='OptionsList',
                    table='ida_optionslist',
                ),
            ],
        ),
    ]
