# Generated by Django 2.1.7 on 2019-04-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0034_attribute_type_same_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='dt_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='dt_fields',
            name='dte_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
