# Generated by Django 2.1.7 on 2019-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0035_auto_20190419_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='nowrap',
            field=models.BooleanField(default=False),
        ),
    ]
