# Generated by Django 4.2.2 on 2023-12-16 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0023_location_alter_organization_location_and_more'),
        ('dalme_app', '0035_alter_attributetype_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Location',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Location',
                    table='ida_location',
                ),
            ],
        )
    ]
