# Generated by Django 4.2.2 on 2023-12-16 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0036_delete_location'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='entityphrase',
                    name='content_type',
                ),
                migrations.RemoveField(
                    model_name='entityphrase',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='entityphrase',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='entityphrase',
                    name='transcription_id',
                ),
            ],
            database_operations=[],
        ),
    ]
