# Generated by Django 2.1.7 on 2019-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0036_dt_fields_nowrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='dte_opts',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
