# Generated by Django 4.2.2 on 2023-12-16 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0024_entityphrase_alter_token_object_phrase_id'),
        ('dalme_app', '0037_remove_entityphrase_content_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='EntityPhrase',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='EntityPhrase',
                    table='ida_entityphrase',
                ),
            ],
        )
    ]
