# Generated by Django 2.1.7 on 2019-04-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0038_auto_20190420_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='filter_options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
