# Generated by Django 4.2.2 on 2023-12-16 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0038_delete_entityphrase'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='objectattribute',
                    name='attribute_concept',
                ),
                migrations.RemoveField(
                    model_name='objectattribute',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='objectattribute',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='objectattribute',
                    name='obj',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Object',
                ),
                migrations.DeleteModel(
                    name='ObjectAttribute',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Object',
                    table='ida_object',
                ),
                migrations.AlterModelTable(
                    name='ObjectAttribute',
                    table='ida_objectattribute',
                ),
            ],
        ),
    ]
