# Generated by Django 4.2.2 on 2023-12-16 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0039_remove_objectattribute_attribute_concept_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='contenttypeextended',
                    name='attribute_types',
                ),
                migrations.RemoveField(
                    model_name='contenttypeextended',
                    name='contenttype_ptr',
                ),
                migrations.RemoveField(
                    model_name='contenttypeextended',
                    name='parent',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ContentAttributes',
                ),
                migrations.DeleteModel(
                    name='ContentTypeExtended',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='ContentAttributes',
                    table='ida_contentattributes',
                ),
                migrations.AlterModelTable(
                    name='ContentTypeExtended',
                    table='ida_contenttypeextended',
                ),
            ],
        ),
    ]
