# Generated by Django 2.1.7 on 2019-04-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0040_transcription_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_attributes',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute_type'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent_source',
            field=models.ForeignKey(db_column='parent_source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Source'),
        ),
        migrations.AlterField(
            model_name='source_pages',
            name='transcription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Transcription'),
        ),
    ]
