# Generated by Django 4.2.2 on 2023-12-16 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0040_remove_contenttypeextended_attribute_types_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='countryreference',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='countryreference',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='languagereference',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='languagereference',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='languagereference',
                    name='parent',
                ),
                migrations.AlterUniqueTogether(
                    name='localereference',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='localereference',
                    name='country',
                ),
                migrations.RemoveField(
                    model_name='localereference',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='localereference',
                    name='modification_user',
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AttributeReference',
                ),
                migrations.DeleteModel(
                    name='CountryReference',
                ),
                migrations.DeleteModel(
                    name='LanguageReference',
                ),
                migrations.DeleteModel(
                    name='LocaleReference',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='AttributeReference',
                    table='ida_attributereference',
                ),
                migrations.AlterModelTable(
                    name='CountryReference',
                    table='ida_countryreference',
                ),
                migrations.AlterModelTable(
                    name='LanguageReference',
                    table='ida_languagereference',
                ),
                migrations.AlterModelTable(
                    name='LocaleReference',
                    table='ida_localereference',
                ),
            ],
        ),
    ]
