# Generated by Django 2.1.7 on 2019-04-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0041_auto_20190421_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Notes',
        ),
    ]
