# Generated by Django 4.2.2 on 2023-12-18 10:53
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0028_attributetype_alter_contentattributes_attribute_type_and_more'),
        ('dalme_app', '0041_remove_countryreference_creation_user_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attribute',
                    name='attribute_type',
                    field=models.ForeignKey(
                        db_column='attribute_type',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attributes',
                        to='ida.attributetype',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AttributeType',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='AttributeType',
                    table='ida_attributetype',
                ),
            ],
        ),
    ]
