# Generated by Django 4.2.2 on 2023-12-18 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0042_alter_attribute_attribute_type_delete_attributetype'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='folio',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='folio',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='folio',
                    name='page',
                ),
                migrations.RemoveField(
                    model_name='folio',
                    name='record',
                ),
                migrations.RemoveField(
                    model_name='folio',
                    name='transcription',
                ),
                migrations.RemoveField(
                    model_name='record',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='record',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='record',
                    name='owner',
                ),
                migrations.RemoveField(
                    model_name='record',
                    name='pages',
                ),
                migrations.RemoveField(
                    model_name='record',
                    name='parent_type',
                ),
                migrations.RemoveField(
                    model_name='recordgroup',
                    name='creation_user',
                ),
                migrations.RemoveField(
                    model_name='recordgroup',
                    name='modification_user',
                ),
                migrations.RemoveField(
                    model_name='recordgroup',
                    name='owner',
                ),
                migrations.RemoveField(
                    model_name='recordgroup',
                    name='parent_type',
                ),
            ],
            database_operations=[],
        ),
    ]
