# Generated by Django 2.1.7 on 2019-04-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0043_auto_20190424_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.AlterUniqueTogether(
            name='tasklist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='group',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
