# Generated by Django 2.1.7 on 2019-04-26 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0045_worksets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worksets',
            new_name='Workset',
        ),
    ]
