# Generated by Django 4.2.2 on 2023-12-18 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0045_remove_attributevaluebool_attribute_ptr_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='rs_collection',
                ),
                migrations.DeleteModel(
                    name='rs_collection_resource',
                ),
                migrations.DeleteModel(
                    name='rs_resource',
                ),
                migrations.DeleteModel(
                    name='rs_resource_data',
                ),
                migrations.DeleteModel(
                    name='rs_resource_type_field',
                ),
                migrations.DeleteModel(
                    name='rs_user',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='rs_collection',
                    table='collection',
                ),
                migrations.AlterModelTable(
                    name='rs_collection_resource',
                    table='collection_resource',
                ),
                migrations.AlterModelTable(
                    name='rs_resource',
                    table='resource',
                ),
                migrations.AlterModelTable(
                    name='rs_resource_data',
                    table='resource_data',
                ),
                migrations.AlterModelTable(
                    name='rs_resource_type_field',
                    table='resource_type_field',
                ),
                migrations.AlterModelTable(
                    name='rs_user',
                    table='user',
                ),
            ],
        )
    ]
