# Generated by Django 2.1.7 on 2019-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0046_auto_20190426_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='position',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
