# Generated by Django 2.1.7 on 2019-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_attachment'),
        ('dalme_app', '0047_auto_20190426_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='todo.Task')),
                ('workset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Workset')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='par_folio',
            name='inv_id',
        ),
        migrations.DeleteModel(
            name='par_object',
        ),
        migrations.RemoveField(
            model_name='par_token',
            name='folio_id',
        ),
        migrations.DeleteModel(
            name='par_folio',
        ),
        migrations.DeleteModel(
            name='par_inventory',
        ),
        migrations.DeleteModel(
            name='par_token',
        ),
    ]
