# Generated by Django 2.1.7 on 2019-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0048_auto_20190427_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dt_list',
            name='default_headers',
        ),
        migrations.RemoveField(
            model_name='dt_list',
            name='extra_headers',
        ),
    ]
