# Generated by Django 2.1.7 on 2019-04-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0049_auto_20190427_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
