# Generated by Django 2.1.7 on 2019-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0052_auto_20190504_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='filter_match',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
