# Generated by Django 2.1.7 on 2019-05-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0054_remove_dt_fields_filter_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
