# Generated by Django 2.1.7 on 2019-05-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0056_auto_20190506_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_type',
            name='short_name',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='content_class',
            name='short_name',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='content_type',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='short_name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
