# Generated by Django 2.1.7 on 2019-05-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0057_auto_20190506_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_list',
            name='helpers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
