# Generated by Django 2.1.7 on 2019-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0058_dt_list_helpers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dt_list',
            name='form_helper',
        ),
        migrations.RemoveField(
            model_name='dt_list',
            name='preview_helper',
        ),
    ]
