# Generated by Django 2.1.7 on 2019-05-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0059_auto_20190506_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_type',
            field=models.CharField(blank=True, choices=[('checkbox', 'checkbox'), ('chosen', 'chosen'), ('date', 'date'), ('datetime', 'datetime'), ('hidden', 'hidden'), ('password', 'password'), ('radio', 'radio'), ('readonly', 'readonly'), ('select', 'select'), ('text', 'text'), ('textarea', 'textarea'), ('upload', 'upload'), ('uploadMany', 'uploadMany')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(blank=True, choices=[('contains', 'contains'), ('date', 'date'), ('day', 'day'), ('endswith', 'endswith'), ('exact', 'exact'), ('gt', 'gt'), ('gte', 'gte'), ('hour', 'hour'), ('icontains', 'icontains'), ('iendswith', 'iendswith'), ('iexact', 'iexact'), ('in', 'in'), ('iregex', 'iregex'), ('isnull', 'isnull'), ('istartswith', 'istartswith'), ('lt', 'lt'), ('lte', 'lte'), ('minute', 'minute'), ('month', 'month'), ('quarter', 'quarter'), ('range', 'range'), ('regex', 'regex'), ('second', 'second'), ('startswith', 'startswith'), ('time', 'time'), ('week', 'week'), ('week_day', 'week_day'), ('year', 'year')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_mode',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('complete', 'complete'), ('strict', 'strict')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('select', 'select'), ('switch', 'switch'), ('text', 'text')], max_length=55, null=True),
        ),
    ]
