# Generated by Django 2.1.7 on 2019-05-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0060_auto_20190506_1600'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dt_fields',
            unique_together={('list', 'field')},
        ),
    ]
