# Generated by Django 2.1.7 on 2019-05-08 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0061_auto_20190506_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='dte_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content_attributes',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_types', to='dalme_app.Attribute_type'),
        ),
    ]
