# Generated by Django 2.1.7 on 2019-05-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0062_auto_20190508_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_type',
            name='content_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dalme_app.Content_class'),
        ),
    ]
