# Generated by Django 2.1.7 on 2019-05-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0063_auto_20190508_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_attributes',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_type_list', to='dalme_app.Content_type'),
        ),
    ]
