# Generated by Django 2.1.7 on 2019-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0064_auto_20190508_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wp_role',
            field=models.CharField(choices=[('a:1:{s:10:"subscriber";b:1;}', 'Subscriber'), ('a:1:{s:11:"contributor";b:1;}', 'Contributor'), ('a:1:{s:6:"author";b:1;}', 'Author'), ('a:1:{s:6:"editor";b:1;}', 'Editor'), ('a:1:{s:13:"administrator";b:1;}', 'Administrator')], max_length=50, null=True),
        ),
    ]
