# Generated by Django 2.1.7 on 2019-05-09 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0066_auto_20190509_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute_type',
            name='data_type',
            field=models.CharField(choices=[('check', 'check'), ('select', 'select'), ('switch', 'switch'), ('text', 'text')], max_length=15),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='same_as',
            field=models.ForeignKey(db_column='same_as', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Attribute_type'),
        ),
    ]
