# Generated by Django 2.1.7 on 2019-05-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0069_auto_20190509_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_attributes',
            name='order',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_type',
            field=models.CharField(blank=True, choices=[('autoComplete', 'autoComplete'), ('checkbox', 'checkbox'), ('chosen', 'chosen'), ('date', 'date'), ('datetime', 'datetime'), ('hidden', 'hidden'), ('multi-chosen', 'multi-chosen'), ('password', 'password'), ('radio', 'radio'), ('readonly', 'readonly'), ('select', 'select'), ('text', 'text'), ('textarea', 'textarea'), ('upload', 'upload'), ('uploadMany', 'uploadMany')], max_length=55, null=True),
        ),
    ]
