# Generated by Django 2.1.7 on 2019-05-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0070_auto_20190510_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(db_column='attribute_type', on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Attribute_type'),
        ),
    ]
