# Generated by Django 2.1.7 on 2019-05-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0071_auto_20190510_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='dte_class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
