# Generated by Django 2.1.7 on 2019-05-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0072_dt_fields_dte_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dt_fields',
            old_name='dte_class_name',
            new_name='dt_class_name',
        ),
    ]
