# Generated by Django 2.1.7 on 2019-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0075_dt_fields_dte_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dt_fields',
            name='order',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
