# Generated by Django 2.1.7 on 2019-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0076_dt_fields_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(blank=True, choices=[('__contains', 'contains'), ('__date', 'date'), ('__day', 'day'), ('__endswith', 'endswith'), ('__exact', 'exact'), ('__gt', 'gt'), ('__gte', 'gte'), ('__hour', 'hour'), ('__icontains', 'icontains'), ('__iendswith', 'iendswith'), ('__iexact', 'iexact'), ('__in', 'in'), ('__iregex', 'iregex'), ('__isnull', 'isnull'), ('__istartswith', 'istartswith'), ('__lt', 'lt'), ('__lte', 'lte'), ('__minute', 'minute'), ('__month', 'month'), ('__quarter', 'quarter'), ('__range', 'range'), ('__regex', 'regex'), ('__second', 'second'), ('__startswith', 'startswith'), ('__time', 'time'), ('__week', 'week'), ('__week_day', 'week_day'), ('__year', 'year')], max_length=55, null=True),
        ),
    ]
