# Generated by Django 2.1.7 on 2019-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0079_auto_20190512_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_type',
            field=models.CharField(choices=[('check', 'check'), ('select', 'select'), ('switch', 'switch'), ('text', 'text'), ('date', 'date'), ('datetime', 'datetime'), ('integer', 'integer')], default=None, max_length=55, null=True),
        ),
    ]
