# Generated by Django 2.1.7 on 2019-05-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0080_auto_20190512_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dt_fields',
            name='dte_class_name',
        ),
        migrations.RemoveField(
            model_name='dt_fields',
            name='filter_operator',
        ),
    ]
