# Generated by Django 2.1.7 on 2019-05-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0081_auto_20190512_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dt_fields',
            name='nowrap',
        ),
    ]
