# Generated by Django 2.1.7 on 2019-05-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0083_content_attributes_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_STR',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_TXT',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='attributereference',
            name='term_type',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_class_name',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_name',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_width',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_message',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_name',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_options',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_opts',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_type',
            field=models.CharField(blank=True, choices=[('autoComplete', 'autoComplete'), ('checkbox', 'checkbox'), ('chosen', 'chosen'), ('date', 'date'), ('datetime', 'datetime'), ('hidden', 'hidden'), ('multi-chosen', 'multi-chosen'), ('password', 'password'), ('radio', 'radio'), ('readonly', 'readonly'), ('select', 'select'), ('text', 'text'), ('textarea', 'textarea'), ('upload', 'upload'), ('uploadMany', 'uploadMany')], default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(blank=True, choices=[('__contains', 'contains'), ('__date', 'date'), ('__day', 'day'), ('__endswith', 'endswith'), ('__exact', 'exact'), ('__gt', 'gt'), ('__gte', 'gte'), ('__hour', 'hour'), ('__icontains', 'icontains'), ('__iendswith', 'iendswith'), ('__iexact', 'iexact'), ('__in', 'in'), ('__iregex', 'iregex'), ('__isnull', 'isnull'), ('__istartswith', 'istartswith'), ('__lt', 'lt'), ('__lte', 'lte'), ('__minute', 'minute'), ('__month', 'month'), ('__quarter', 'quarter'), ('__range', 'range'), ('__regex', 'regex'), ('__second', 'second'), ('__startswith', 'startswith'), ('__time', 'time'), ('__week', 'week'), ('__week_day', 'week_day'), ('__year', 'year')], default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_mode',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('complete', 'complete'), ('strict', 'strict')], default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_options',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('select', 'select'), ('switch', 'switch'), ('text', 'text'), ('date', 'date'), ('datetime', 'datetime'), ('integer', 'integer')], default=None, max_length=55),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='render_exp',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='api_url',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='helpers',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='dam_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wp_role',
            field=models.CharField(blank=True, choices=[('a:1:{s:10:"subscriber";b:1;}', 'Subscriber'), ('a:1:{s:11:"contributor";b:1;}', 'Contributor'), ('a:1:{s:6:"author";b:1;}', 'Author'), ('a:1:{s:6:"editor";b:1;}', 'Editor'), ('a:1:{s:13:"administrator";b:1;}', 'Administrator')], default='a:1:{s:10:"subscriber";b:1;}', max_length=50),
        ),
        migrations.AlterField(
            model_name='source_pages',
            name='transcription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Transcription'),
        ),
        migrations.AlterField(
            model_name='task',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='body',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='email_from',
            field=models.CharField(blank=True, default=None, max_length=320),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='email_message_id',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='transcription',
            field=models.TextField(blank=True, default=None),
        ),
    ]
