# Generated by Django 2.1.7 on 2019-05-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0084_auto_20190517_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute_type',
            name='options_list',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
