# Generated by Django 2.1.7 on 2019-05-18 17:37

import dalme_app.middleware
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0085_attribute_type_options_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.middleware.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('glottolog_id', models.CharField(max_length=25)),
                ('iso6393_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=55)),
                ('type', models.CharField(choices=[('language', 'language'), ('dialect', 'dialect')], max_length=15)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
