# Generated by Django 2.1.7 on 2019-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0087_auto_20190518_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso6393_id',
            field=models.CharField(blank=True, default=None, max_length=15, unique=True),
        ),
    ]
