# Generated by Django 2.1.7 on 2019-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0090_auto_20190518_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso6393_id',
            field=models.CharField(blank=True, default=None, max_length=25, null=True, unique=True),
        ),
    ]
