# Generated by Django 2.1.7 on 2019-05-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0091_auto_20190518_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='glottolog_id',
            new_name='glottocode',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='iso6393_id',
            new_name='iso6393',
        ),
    ]
