# Generated by Django 2.1.7 on 2019-05-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0092_auto_20190518_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='parent_source',
        ),
        migrations.AddField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Source'),
        ),
    ]
