# Generated by Django 2.1.7 on 2019-05-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0093_auto_20190518_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_STR',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='options_list',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_class_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dt_width',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_message',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_name',
            field=models.CharField(blank=True, default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_options',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_opts',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='dte_type',
            field=models.CharField(blank=True, choices=[('autoComplete', 'autoComplete'), ('checkbox', 'checkbox'), ('chosen', 'chosen'), ('date', 'date'), ('datetime', 'datetime'), ('hidden', 'hidden'), ('multi-chosen', 'multi-chosen'), ('password', 'password'), ('radio', 'radio'), ('readonly', 'readonly'), ('select', 'select'), ('text', 'text'), ('textarea', 'textarea'), ('upload', 'upload'), ('uploadMany', 'uploadMany')], default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(blank=True, choices=[('__contains', 'contains'), ('__date', 'date'), ('__day', 'day'), ('__endswith', 'endswith'), ('__exact', 'exact'), ('__gt', 'gt'), ('__gte', 'gte'), ('__hour', 'hour'), ('__icontains', 'icontains'), ('__iendswith', 'iendswith'), ('__iexact', 'iexact'), ('__in', 'in'), ('__iregex', 'iregex'), ('__isnull', 'isnull'), ('__istartswith', 'istartswith'), ('__lt', 'lt'), ('__lte', 'lte'), ('__minute', 'minute'), ('__month', 'month'), ('__quarter', 'quarter'), ('__range', 'range'), ('__regex', 'regex'), ('__second', 'second'), ('__startswith', 'startswith'), ('__time', 'time'), ('__week', 'week'), ('__week_day', 'week_day'), ('__year', 'year')], default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_mode',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('complete', 'complete'), ('strict', 'strict')], default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_options',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('check', 'check'), ('select', 'select'), ('switch', 'switch'), ('text', 'text'), ('date', 'date'), ('datetime', 'datetime'), ('integer', 'integer')], default=None, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='dt_fields',
            name='render_exp',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='api_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dt_list',
            name='helpers',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
