# Generated by Django 2.1.7 on 2019-05-22 16:04

import dalme_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0096_auto_20190521_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('num_code', models.IntegerField()),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
    ]
