# Generated by Django 2.2.1 on 2019-05-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0099_auto_20190524_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_pages',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='dalme_app.Page'),
        ),
    ]
