# Generated by Django 2.2.1 on 2019-06-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0104_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='short_name',
            new_name='name',
        ),
    ]
