# Generated by Django 2.2.1 on 2019-06-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0106_remove_dt_fields_filter_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dt_fields',
            name='filter_lookup',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
