# Generated by Django 2.2.1 on 2019-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0107_auto_20190602_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workset',
            old_name='query',
            new_name='qset',
        ),
        migrations.AddField(
            model_name='workset',
            name='endpoint',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='workset',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
