# Generated by Django 2.2.1 on 2019-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0108_auto_20190602_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='endpoint',
            field=models.CharField(max_length=55),
        ),
    ]
