# Generated by Django 2.2.1 on 2019-06-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0109_auto_20190602_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='progress',
            field=models.IntegerField(null=True),
        ),
    ]
