# Generated by Django 2.2.1 on 2019-06-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0110_auto_20190602_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='workset',
            name='current_record',
            field=models.IntegerField(null=True),
        ),
    ]
