# Generated by Django 2.2.1 on 2019-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0111_workset_current_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='current_record',
            field=models.IntegerField(default=1),
        ),
    ]
