# Generated by Django 2.2.1 on 2019-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0112_auto_20190603_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
