# Generated by Django 2.2.1 on 2019-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0113_auto_20190603_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workset',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
