# Generated by Django 2.2.1 on 2019-06-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0115_auto_20190603_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
