# Generated by Django 2.2.1 on 2019-06-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0118_auto_20190604_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
