# Generated by Django 2.2.1 on 2019-06-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0120_auto_20190604_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_name',
        ),
    ]
