# Generated by Django 2.2.1 on 2019-06-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0124_auto_20190604_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
    ]
