# Generated by Django 2.2.1 on 2019-06-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0125_auto_20190604_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_number',
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.CharField(db_index=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.CharField(db_index=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
