# Generated by Django 2.2.1 on 2019-06-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0126_auto_20190604_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
    ]
