# Generated by Django 2.2.1 on 2019-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0127_auto_20190604_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
