# Generated by Django 2.2.1 on 2019-06-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0128_attachment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
