# Generated by Django 2.2.2 on 2019-07-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0129_auto_20190607_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='is_inventory',
            new_name='has_inventory',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.TaskList'),
            preserve_default=False,
        ),
    ]
