# Generated by Django 2.2.2 on 2019-07-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0130_auto_20190725_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_type',
            name='has_pages',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='content_type',
            name='parents',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
