# Generated by Django 2.2.2 on 2019-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0131_auto_20190725_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_type',
            name='has_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
