# Generated by Django 2.2.2 on 2019-07-31 16:03

import dalme_app.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0132_content_type_has_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='workflow', serialize=False, to='dalme_app.Source')),
                ('status', models.CharField(choices=[(1, 'Processing'), (2, 'Awaiting Review'), (3, 'Under Review'), (4, 'Processed')], max_length=1)),
                ('stage', models.CharField(choices=[(1, 'Ingestion'), (2, 'Transcription'), (3, 'Markup'), (4, 'Parsing')], max_length=1)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_user', models.CharField(blank=True, max_length=255, null=True)),
                ('help_flag', models.BooleanField(default=False)),
                ('ingestion_done', models.BooleanField(default=False)),
                ('transcription_done', models.BooleanField(default=False)),
                ('markup_done', models.BooleanField(default=False)),
                ('parsing_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work_log',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('event', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(default=dalme_app.models._templates.get_current_user, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Workflow')),
            ],
        ),
    ]
