# Generated by Django 2.2.2 on 2019-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0133_work_log_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='stage',
            field=models.CharField(blank=True, choices=[(1, 'Ingestion'), (2, 'Transcription'), (3, 'Markup'), (4, 'Parsing')], max_length=1, null=True),
        ),
    ]
