# Generated by Django 2.2.2 on 2019-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0134_auto_20190731_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Awaiting Review'), (3, 'Under Review'), (4, 'Processed')], default=0),
        ),
    ]
