# Generated by Django 2.2.2 on 2019-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0135_auto_20190731_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Ingestion'), (2, 'Transcription'), (3, 'Markup'), (4, 'Parsing')], default=0),
        ),
    ]
