# Generated by Django 2.2.2 on 2019-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0136_auto_20190731_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='status',
        ),
        migrations.AddField(
            model_name='workflow',
            name='review_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='wf_status',
            field=models.IntegerField(choices=[(1, 'assessing'), (2, 'processing'), (3, 'processed')], default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='stage',
            field=models.IntegerField(choices=[(1, 'ingestion'), (2, 'transcription'), (3, 'markup'), (5, 'review'), (4, 'parsing')], default=1),
        ),
    ]
