# Generated by Django 2.2.2 on 2019-08-02 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0138_auto_20190731_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_pages',
            name='transcription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='dalme_app.Transcription'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='stage',
            field=models.IntegerField(choices=[(1, 'ingestion'), (2, 'transcription'), (3, 'markup'), (4, 'review'), (5, 'parsing')], default=1),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='wf_status',
            field=models.IntegerField(choices=[(1, 'assessing'), (2, 'processing'), (3, 'processed')], default=2),
        ),
    ]
