# Generated by Django 3.0.1 on 2020-03-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0140_auto_20190806_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
