# Generated by Django 3.0.1 on 2020-04-08 16:14

import dalme_app.utils
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dalme_app', '0142_auto_20200323_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity_phrase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('phrase', models.TextField(blank=True)),
                ('type', models.IntegerField(choices=[(1, 'Agent'), (2, 'Object'), (3, 'Place')])),
                ('object_id', models.UUIDField(db_index=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('transcription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_phrases', to='dalme_app.Transcription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('source_object_id', models.UUIDField(db_index=True, null=True)),
                ('target_object_id', models.UUIDField(db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RightsPolicy',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('rights_status', models.IntegerField(choices=[(1, 'Copyrighted'), (2, 'Orphaned'), (3, 'Owned'), (4, 'Public Domain'), (5, 'Unknown')], default=5)),
                ('rights', models.TextField(blank=True, default=None)),
                ('rights_notice', models.TextField(blank=True, default=None)),
                ('licence', models.TextField(blank=True, default=None, null=True)),
                ('rights_holder', models.CharField(default=None, max_length=255, null=True)),
                ('notice_display', models.BooleanField(default=False)),
                ('attachments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.Attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_username', models.CharField(blank=True, default=dalme_app.models._templates.get_current_username, max_length=255, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Temporal'), (2, 'Spatial'), (3, 'Linguistic'), (4, 'Context')])),
                ('range', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='CityReference',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='CountryReference',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='LanguageReference',
        ),
        migrations.RemoveField(
            model_name='identity_phrase_x_entity',
            name='identity_phrase_id',
        ),
        migrations.RemoveField(
            model_name='object_phrase',
            name='transcription',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['creation_timestamp']},
        ),
        migrations.RenameField(
            model_name='object_attribute',
            old_name='object_id',
            new_name='object',
        ),
        migrations.RemoveField(
            model_name='object',
            name='concept_id',
        ),
        migrations.RemoveField(
            model_name='object',
            name='object_phrase_id',
        ),
        migrations.RemoveField(
            model_name='object_attribute',
            name='concept_id',
        ),
        migrations.AddField(
            model_name='agent',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='std_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content_type',
            name='r1_inheritance',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='content_type',
            name='r2_inheritance',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='concept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Concept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object_attribute',
            name='attribute_concept',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Concept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='std_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='has_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Person'), (2, 'Organization')]),
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='data_type',
            field=models.CharField(choices=[('DATE', 'DATE (date)'), ('INT', 'INT (integer)'), ('STR', 'STR (string)'), ('TXT', 'TXT (text)'), ('UUID', 'UUID (DALME record)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='object_attribute',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source_pages',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pages', to='dalme_app.Source'),
        ),
        migrations.DeleteModel(
            name='Identity_phrase',
        ),
        migrations.DeleteModel(
            name='Identity_phrase_x_entity',
        ),
        migrations.AddField(
            model_name='relationship',
            name='scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Scope'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='source_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_sources', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='target_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_targets', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='token',
            name='object_phrase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dalme_app.Entity_phrase'),
        ),
        migrations.DeleteModel(
            name='Object_phrase',
        ),
    ]
