# Generated by Django 3.0.1 on 2020-06-30 15:14

import dalme_app.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0143_auto_20200408_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_agent_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_agent_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_agent_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attachment_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attachment_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attachment_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute_type',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_type_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute_type',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_type_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute_type',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attribute_type_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributereference',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attributereference_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributereference',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attributereference_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attributereference',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_attributereference_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityreference',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_cityreference_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityreference',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_cityreference_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cityreference',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_cityreference_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_comment_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_comment_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_comment_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_concept_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_concept_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concept',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_concept_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_attributes_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_attributes_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_attributes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_attributes_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_class',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_class_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_class',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_class_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_class',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_class_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_type',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_type_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_type',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_type_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content_type',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_content_type_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countryreference',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_countryreference_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countryreference',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_countryreference_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countryreference',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_countryreference_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_fields',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_fields_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_fields',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_fields_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_fields',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_fields_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_list',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_list_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_list',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_list_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dt_list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_dt_list_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity_phrase',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_entity_phrase_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity_phrase',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_entity_phrase_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity_phrase',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_entity_phrase_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headword',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_headword_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headword',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_headword_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='headword',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_headword_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languagereference',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_languagereference_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languagereference',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_languagereference_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='languagereference',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_languagereference_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object_attribute',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_attribute_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object_attribute',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_attribute_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='object_attribute',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_object_attribute_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_page_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_page_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_page_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_place_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_place_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_place_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_relationship_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_relationship_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_relationship_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rightspolicy',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_rightspolicy_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rightspolicy',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_rightspolicy_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rightspolicy',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_rightspolicy_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scope',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_scope_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scope',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_scope_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scope',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_scope_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='owner_local',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set_x_content',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_x_content_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set_x_content',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_x_content_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set_x_content',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_x_content_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source_pages',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_pages_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source_pages',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_pages_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source_pages',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_pages_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tag_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tag_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tag_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_task_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_task_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_task_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tasklist_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tasklist_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_tasklist_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_ticket_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_ticket_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_ticket_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_token_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_token_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='token',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_token_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcription',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_transcription_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcription',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_transcription_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcription',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_transcription_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordform',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_wordform_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordform',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_wordform_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordform',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_wordform_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='set',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_set_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work_log',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_log', to='dalme_app.Workflow'),
        ),
    ]
