# Generated by Django 2.2.4 on 2020-06-25 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0143_auto_20200408_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_log',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_log', to='dalme_app.Workflow'),
        ),
    ]
