# Generated by Django 3.0.1 on 2020-08-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0144_auto_20200630_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='count_ignore',
            field=models.BooleanField(default=False),
        ),
    ]
