# Generated by Django 3.0.1 on 2020-08-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0145_transcription_count_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='stat_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='stat_title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
