# Generated by Django 3.1 on 2020-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0146_auto_20200813_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='stat_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='stat_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
