# Generated by Django 3.1 on 2020-08-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0148_auto_20200819_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='set_permissions',
            new_name='permissions',
        ),
    ]
