# Generated by Django 3.1 on 2020-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0150_auto_20200824_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wiki_page',
        ),
        migrations.DeleteModel(
            name='wiki_user',
        ),
        migrations.DeleteModel(
            name='wiki_user_groups',
        ),
        migrations.DeleteModel(
            name='wp_usermeta',
        ),
        migrations.DeleteModel(
            name='wp_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dam_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wiki_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wp_role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wp_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='dam_group',
            field=models.CharField(blank=True, choices=[('dam_administrators', 'Administrators'), ('dam_archivists', 'Archivists'), ('dam_general_users', 'General Users'), ('dam_restricted_user', 'Restricted User'), ('dam_super_admin', 'Super Admin')], default='dam_restricted_user', max_length=50),
        ),
    ]
