# Generated by Django 3.1 on 2020-08-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0151_auto_20200825_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dam_group',
        ),
    ]
