# Generated by Django 3.1 on 2020-08-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0152_remove_profile_dam_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
