# Generated by Django 3.1 on 2020-08-26 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dalme_app', '0153_remove_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='owner_local',
        ),
        migrations.AddField(
            model_name='set',
            name='dataset_usergroup',
            field=models.ForeignKey(limit_choices_to={'properties__type': 3}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='auth.group'),
        ),
        migrations.CreateModel(
            name='GroupProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Admin'), (2, 'DAM'), (3, 'Dataset'), (4, 'Knowledge Base'), (5, 'Website')])),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='auth.group')),
            ],
        ),
    ]
