# Generated by Django 3.1 on 2020-09-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0155_auto_20200922_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languagereference',
            name='type',
        ),
        migrations.RemoveField(
            model_name='localereference',
            name='owner',
        ),
        migrations.RenameField(
            model_name='languagereference',
            old_name='lang_type',
            new_name='type',
        )
    ]
