# Generated by Django 3.1 on 2020-08-28 12:59

import dalme_app.model_templates
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0155_source_primary_dataset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityReference',
            new_name='LocaleReference',
        ),
    ]
