# Generated by Django 3.1 on 2020-09-04 16:26

import dalme_app.model_templates
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0156_auto_20200828_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_attributes',
            name='unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='localereference',
            name='creation_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_localereference_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localereference',
            name='modification_user',
            field=models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_localereference_modification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='localereference',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_localereference_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
