# Generated by Django 3.1 on 2020-09-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0156_auto_20200926_1250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='source_credit',
            unique_together={('source', 'agent', 'type')},
        ),
    ]
