# Generated by Django 3.1 on 2020-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0157_auto_20200904_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproperties',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
