# Generated by Django 3.1 on 2020-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0158_groupproperties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
