# Generated by Django 3.1.2 on 2020-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0159_auto_20201031_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightspolicy',
            name='public_display',
            field=models.BooleanField(default=True),
        ),
    ]
