# Generated by Django 3.1 on 2020-09-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dalme_app', '0159_source_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagereference',
            name='lang_type',
            field=models.IntegerField(choices=[(1, 'Language'), (2, 'Dialect')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute_type',
            name='data_type',
            field=models.CharField(choices=[('DATE', 'DATE (date)'), ('INT', 'INT (integer)'), ('STR', 'STR (string)'), ('TXT', 'TXT (text)'), ('FK-UUID', 'FK-UUID (DALME record)'), ('FK-INT', 'FK-INT (DALME record)')], max_length=15),
        ),
    ]
