# Generated by Django 3.1 on 2020-09-19 19:25

import dalme_app.model_templates
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dalme_app', '0161_auto_20200913_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='attribute_type',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='attributereference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='concept',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content_attributes',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content_class',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content_type',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='countryreference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dt_fields',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dt_list',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='entity_phrase',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='headword',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='languagereference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='localereference',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='object',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='object_attribute',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='page',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='place',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='rightspolicy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='set_x_content',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='source_pages',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='wordform',
            name='owner',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_TXT',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dalme_app.source'),
        ),
        migrations.CreateModel(
            name='Source_credit',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Editor'), (2, 'Editor - Corrections'), (3, 'Contributor')])),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_credits', to='dalme_app.agent')),
                ('creation_user', models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_credit_creation', to=settings.AUTH_USER_MODEL)),
                ('modification_user', models.ForeignKey(default=dalme_app.model_templates.get_current_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dalme_app_source_credit_modification', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_credits', to='dalme_app.source')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
