export const columnMap = {
  name: {
    label: "Name",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: true,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  shortName: {
    label: "Short name",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  parent: {
    label: "Parent",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  owner: {
    label: "Owner",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  isPrivate: {
    label: "Private",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap text-center",
    isDefaultVisible: false,
    autoWidth: true,
  },
  noRecords: {
    label: "No. Records",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap text-center",
    isDefaultVisible: true,
    autoWidth: true,
  },
  creationUser: {
    label: "Created by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  creationTimestamp: {
    label: "Created on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  modificationUser: {
    label: "Modified by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  modificationTimestamp: {
    label: "Modified on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
};
