# Generated by Django 5.0.4 on 2024-12-20 21:56

import modelcluster.fields
import wagtail.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                (
                    'title',
                    models.CharField(help_text='Corpus name or short description to use as title.', max_length=255),
                ),
                ('description', wagtail.fields.RichTextField(help_text='A description of the corpus.')),
                (
                    'collapsed',
                    models.BooleanField(default=False, help_text='If checked the corpus will be initially closed.'),
                ),
                (
                    'collections',
                    modelcluster.fields.ParentalManyToManyField(related_name='corpora', to='web.collection'),
                ),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='corpora', to='web.collections'
                    ),
                ),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
