FROM python:3.6
WORKDIR /app

# Install wait-for-it to wait for mysql database when testing locally
COPY docker/python/wait-for-it.sh /usr/local/bin/
RUN chmod u+x /usr/local/bin/wait-for-it.sh

RUN rm -rf /var/lib/apt/lists/* && apt-get update
RUN apt-get install -y libxml2-dev xmlsec1 libxmlsec1-dev libxmlsec1-openssl --no-install-recommends

COPY requirements*.txt ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements-dev.txt

RUN mkdir -p /opt/python/log && touch /opt/python/log/dalme_app.log && \
    chmod 777 /opt/python/log/dalme_app.log

COPY dalme /app/dalme
COPY dalme_api /app/dalme_api
COPY dalme_app /app/dalme_app
COPY dalme_public /app/dalme_public
COPY dalme_purl /app/dalme_purl
COPY templates /app/templates
COPY manage.py /app/

COPY docker/python/app-entrypoint.sh /usr/local/bin/
RUN chmod u+x /usr/local/bin/app-entrypoint.sh
ENTRYPOINT ["app-entrypoint.sh"]

EXPOSE 8000 8443
CMD ["gunicorn", "-b", "0.0.0.0", "-w", "2", "dalme.wsgi"]
