version: '3'

services:
  static:
    image: static-prod
    build:
        context: '../..'
        dockerfile: 'docker/prod/Dockerfile.static'
    depends_on:
        - web
    network_mode: 'service:web'
    env_file: prod.env
  web:
    image: dalme-prod
    build:
        context: '../..'
        dockerfile: 'docker/prod/Dockerfile.web'
    volumes:
        - ../../:/app
    ports:
      - "8443:8843"
    env_file: prod.env
