# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-31 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platonic_concepts', '0003_auto_20170531_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platonicconcept',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='platonicconcept',
            name='modification_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
