# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platonic_concepts', '0005_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='creation_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='creation_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='modification_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='modification_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
