# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platonic_concepts', '0006_auto_20170601_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='platonicconcept',
            name='getty_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
