export const attachmentIcons = {
  "application/gzip": "mdi-file-download",
  "application/json": "mdi-file-table",
  "application/msword": "mdi-file-word",
  "application/pdf": "mdi-file-cad",
  "application/vnd.ms-excel": "mdi-file-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "mdi-file-excel",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "mdi-file-word",
  "application/zip": "mdi-file-download",
  "audio/mpeg": "mdi-file-music",
  "image/gif": "mdi-file-image",
  "image/jpeg": "mdi-file-image",
  "image/png": "mdi-file-image",
  "image/tiff": "mdi-file-image",
  "text/calendar": "mdi-file-clock",
  "text/csv": "mdi-file-delimited",
  "text/html": "mdi-file-link",
  "text/xml": "mdi-file-code",
  "text/plain": "mdi-file-document",
  "video/mp4": "mdi-file-video",
};
