version: '3'

services:
  db:
    image: mysql:8.0.19
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: dalme
        MYSQL_PASSWORD: dalme
        MYSQL_DATABASE: dalme
    volumes:
        - ./.mysql:/docker-entrypoint-initdb.d
        - ./.mysql:/etc/mysql/conf.d
  web:
    image: dalme-web
    build:
        context: ../
        dockerfile: ./.devcontainer/Dockerfile
    volumes:
        - ../:/app
    entrypoint: /app/.devcontainer/docker-entrypoint.sh
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    env_file: .env
    environment:
        DATABASE_URL: mysql://dalme:dalme@db:3306/dalme
