FROM python:3.9

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV LANG=en_US.UTF-8

RUN adduser \
    --disabled-password \
    --gecos "Whisky" \
    --uid 1001 \
    --gid 0 \
    --home /home/whisky whisky && \
    chmod 1777 /home/whisky

RUN rm -rf /var/lib/apt/lists/*
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libxmlsec1-openssl \
    vim \
    xmlsec1
RUN apt-get clean

WORKDIR /opt/app
COPY ./manage.py .
COPY ./requirements.txt ./requirements-dev.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ./requirements-dev.txt

# COPY dalme ./dalme
# COPY ssl-certs ./ssl-certs

COPY ./config/eb/gunicorn.conf.py .
COPY ./config/eb/wait-for-it.sh .
RUN chmod u+x ./wait-for-it.sh

RUN mkdir -p /var/log/django && \
    touch /var/log/django/dalme_app.log && \
    chmod 777 /var/log/django/dalme_app.log

STOPSIGNAL SIGINT