# Generated by Django 5.0.3 on 2024-05-03 19:48

import sortedm2m.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('ida', '0003_casts'),
        ('public', '0001_initial'),
        ('publicgradients', '0001_initial'),
        ('publicimages', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliography',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='collection',
            name='record_collection',
            field=models.ForeignKey(
                help_text='Collection to associate with this page.',
                on_delete=django.db.models.deletion.PROTECT,
                to='ida.collection',
                verbose_name='Collection',
            ),
        ),
        migrations.AddField(
            model_name='collections',
            name='gradient',
            field=models.ForeignKey(
                blank=True,
                help_text='A gradient to overlay on the image.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicgradients.gradient',
            ),
        ),
        migrations.AddField(
            model_name='collections',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='essay',
            name='front_page_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image to use on the front page when this page is featured.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='essay',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='essay',
            name='record',
            field=models.ForeignKey(
                blank=True,
                help_text='A record to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='ida.record',
                verbose_name='Record',
            ),
        ),
        migrations.AddField(
            model_name='essay',
            name='record_collection',
            field=models.ForeignKey(
                blank=True,
                help_text='A collection to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ida.collection',
                verbose_name='Collection',
            ),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='front_page_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image to use on the front page when this page is featured.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='record',
            field=models.ForeignKey(
                help_text='A record to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='ida.record',
                verbose_name='Record',
            ),
        ),
        migrations.AddField(
            model_name='featuredinventory',
            name='record_collection',
            field=models.ForeignKey(
                blank=True,
                help_text='A collection to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ida.collection',
                verbose_name='Collection',
            ),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='front_page_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image to use on the front page when this page is featured.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='record',
            field=models.ForeignKey(
                help_text='A record to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='ida.record',
                verbose_name='Record',
            ),
        ),
        migrations.AddField(
            model_name='featuredobject',
            name='record_collection',
            field=models.ForeignKey(
                blank=True,
                help_text='A collection to associate with this page.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ida.collection',
                verbose_name='Collection',
            ),
        ),
        migrations.AddField(
            model_name='features',
            name='gradient',
            field=models.ForeignKey(
                blank=True,
                help_text='A gradient to overlay on the image.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicgradients.gradient',
            ),
        ),
        migrations.AddField(
            model_name='features',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='flat',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='page',
            field=models.ForeignKey(
                help_text='Page linked to the label.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='wagtailcore.page',
            ),
        ),
        migrations.AddField(
            model_name='home',
            name='gradient',
            field=models.ForeignKey(
                blank=True,
                help_text='A gradient to overlay on the image.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicgradients.gradient',
            ),
        ),
        migrations.AddField(
            model_name='home',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='home',
            name='learn_more_page',
            field=models.ForeignKey(
                blank=True,
                help_text='The page that should open when "Learn more..." is selected.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailcore.page',
            ),
        ),
        migrations.AddField(
            model_name='section',
            name='gradient',
            field=models.ForeignKey(
                blank=True,
                help_text='A gradient to overlay on the image.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicgradients.gradient',
            ),
        ),
        migrations.AddField(
            model_name='section',
            name='header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='browser_header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header of the record browser.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
                verbose_name='Header image',
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='editors',
            field=sortedm2m.fields.SortedManyToManyField(
                help_text='List of editors (in desired order).', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='explore_header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header of the explore page.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
                verbose_name='Header image',
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='search_header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header of the search page.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
                verbose_name='Header image',
            ),
        ),
        migrations.AddField(
            model_name='settings',
            name='viewer_header_image',
            field=models.ForeignKey(
                blank=True,
                help_text='The image that will display in the header of the record viewer.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='publicimages.baseimage',
                verbose_name='Header image',
            ),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ForeignKey(
                help_text='Logo of the sponsor.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='publicimages.baseimage',
            ),
        ),
    ]
