# Generated by Django 5.0.3 on 2024-04-10 01:05

import uuid

import modelcluster.fields
import wagtail.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footnote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', wagtail.fields.RichTextField()),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='footnotes', to='wagtailcore.page'
                    ),
                ),
            ],
            options={
                'unique_together': {('page', 'id')},
            },
        ),
    ]
