FROM node:18-buster-slim

WORKDIR /opt/ui
ENV PATH /opt/dalme_ui/node_modules/.bin:$PATH

COPY ./dalme_ui .
RUN chown -R node:node . && chmod -R 755 .
USER node

RUN yarn install --silent
# RUN yarn cache clean --force  # Add for prod.

CMD ["yarn", "dev"]
STOPSIGNAL SIGINT
