# Generated by Django 5.1.4 on 2025-01-06 20:02

import uuid

import wagtail.search.index

import django.contrib.contenttypes.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import app.context
import domain.models.attribute.attribute_field


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='rs_collection',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user', models.IntegerField(null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('public', models.IntegerField(default='0')),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('theme2', models.CharField(blank=True, max_length=100)),
                ('theme3', models.CharField(blank=True, max_length=100)),
                ('allow_changes', models.IntegerField(default='0')),
                ('cant_delete', models.IntegerField(default='0')),
                ('keywords', models.TextField()),
                ('savedsearch', models.IntegerField(null=True)),
                ('home_page_publish', models.IntegerField(null=True)),
                ('home_page_text', models.TextField()),
                ('home_page_image', models.IntegerField(null=True)),
                ('session_id', models.IntegerField(null=True)),
                ('theme4', models.CharField(blank=True, max_length=100)),
                ('theme5', models.CharField(blank=True, max_length=100)),
                ('theme6', models.CharField(blank=True, max_length=100)),
                ('theme7', models.CharField(blank=True, max_length=100)),
                ('theme8', models.CharField(blank=True, max_length=100)),
                ('theme9', models.CharField(blank=True, max_length=100)),
                ('theme10', models.CharField(blank=True, max_length=100)),
                ('theme11', models.CharField(blank=True, max_length=100)),
                ('theme12', models.CharField(blank=True, max_length=100)),
                ('theme13', models.CharField(blank=True, max_length=100)),
                ('theme14', models.CharField(blank=True, max_length=100)),
                ('theme15', models.CharField(blank=True, max_length=100)),
                ('theme16', models.CharField(blank=True, max_length=100)),
                ('theme17', models.CharField(blank=True, max_length=100)),
                ('theme18', models.CharField(blank=True, max_length=100)),
                ('theme19', models.CharField(blank=True, max_length=100)),
                ('theme20', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_collection_resource',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(null=True)),
                ('use_as_theme_thumbnail', models.IntegerField(null=True)),
                ('purchase_size', models.CharField(blank=True, max_length=10)),
                ('purchase_complete', models.IntegerField(default='0')),
                ('purchase_price', models.FloatField(default='0.00', max_length=10)),
                ('sortorder', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'collection_resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('resource_type', models.IntegerField(null=True)),
                ('has_image', models.IntegerField(default='0')),
                ('is_transcoding', models.IntegerField(default='0')),
                ('hit_count', models.IntegerField(default='0')),
                ('new_hit_count', models.IntegerField(default='0')),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('user_rating', models.IntegerField(null=True)),
                ('user_rating_count', models.IntegerField(null=True)),
                ('user_rating_total', models.IntegerField(null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=200)),
                ('file_extension', models.CharField(blank=True, max_length=10)),
                ('preview_extension', models.CharField(blank=True, max_length=10)),
                ('image_red', models.IntegerField(null=True)),
                ('image_green', models.IntegerField(null=True)),
                ('image_blue', models.IntegerField(null=True)),
                ('thumb_width', models.IntegerField(null=True)),
                ('thumb_height', models.IntegerField(null=True)),
                ('archive', models.IntegerField(default='0')),
                ('access', models.IntegerField(default='0')),
                ('colour_key', models.CharField(blank=True, max_length=5)),
                ('created_by', models.IntegerField(null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_modified', models.DateTimeField(blank=True, null=True)),
                ('file_checksum', models.CharField(blank=True, max_length=32)),
                ('request_count', models.IntegerField(default='0')),
                ('expiry_notification_sent', models.IntegerField(default='0')),
                ('preview_tweaks', models.CharField(blank=True, max_length=50)),
                ('geo_lat', models.FloatField(default=None, null=True)),
                ('geo_long', models.FloatField(default=None, null=True)),
                ('mapzoom', models.IntegerField(null=True)),
                ('disk_usage', models.IntegerField(null=True)),
                ('disk_usage_last_updated', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=None, null=True)),
                ('preview_attempts', models.IntegerField(default=None, null=True)),
                ('field12', models.CharField(blank=True, default=None, max_length=200)),
                ('field8', models.CharField(blank=True, default=None, max_length=200)),
                ('field3', models.CharField(blank=True, default=None, max_length=200)),
                ('annotation_count', models.IntegerField(null=True)),
                ('field51', models.CharField(blank=True, default=None, max_length=200)),
                ('field79', models.CharField(blank=True, default=None, max_length=200)),
                ('modified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'resource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource_data',
            fields=[
                ('django_id', models.IntegerField(db_column='django_id', primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'resource_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_resource_type_field',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('type', models.IntegerField(null=True)),
                ('order_by', models.IntegerField(default='0')),
                ('keywords_index', models.IntegerField(default='0')),
                ('partial_index', models.IntegerField(default='0')),
                ('resource_type', models.IntegerField(default='0')),
                ('resource_column', models.CharField(blank=True, max_length=50)),
                ('display_field', models.IntegerField(default='1')),
                ('use_for_similar', models.IntegerField(default='1')),
                ('iptc_equiv', models.CharField(blank=True, max_length=20)),
                ('display_template', models.TextField()),
                ('tab_name', models.CharField(blank=True, max_length=50)),
                ('required', models.IntegerField(default='0')),
                ('smart_theme_name', models.CharField(blank=True, max_length=200)),
                ('exiftool_field', models.CharField(blank=True, max_length=200)),
                ('advanced_search', models.IntegerField(default='1')),
                ('simple_search', models.IntegerField(default='0')),
                ('help_text', models.TextField()),
                ('display_as_dropdown', models.IntegerField(default='0')),
                ('external_user_access', models.IntegerField(default='1')),
                ('autocomplete_macro', models.TextField()),
                ('hide_when_uploading', models.IntegerField(default='0')),
                ('hide_when_restricted', models.IntegerField(default='0')),
                ('value_filter', models.TextField()),
                ('exiftool_filter', models.TextField()),
                ('omit_when_copying', models.IntegerField(default='0')),
                ('tooltip_text', models.TextField()),
                ('regexp_filter', models.CharField(blank=True, max_length=400)),
                ('sync_field', models.IntegerField(null=True)),
                ('display_condition', models.CharField(blank=True, max_length=400)),
                ('onchange_macro', models.TextField()),
                ('field_constraint', models.IntegerField(null=True)),
                ('linked_data_field', models.TextField()),
                ('automatic_nodes_ordering', models.IntegerField(default='0')),
                ('fits_field', models.CharField(blank=True, max_length=255)),
                ('personal_data', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'resource_type_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='rs_user',
            fields=[
                ('ref', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, max_length=64)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                (
                    'usergroup',
                    models.IntegerField(
                        choices=[(2, 'General User'), (4, 'Archivist'), (1, 'Administrator'), (3, 'Super Admin')],
                        null=True,
                    ),
                ),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('logged_in', models.IntegerField(null=True)),
                ('last_browser', models.TextField()),
                ('last_ip', models.CharField(blank=True, max_length=100)),
                ('current_collection', models.IntegerField(null=True)),
                ('accepted_terms', models.IntegerField(default='0')),
                ('account_expires', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField()),
                ('session', models.CharField(blank=True, max_length=50)),
                ('ip_restrict', models.TextField()),
                ('search_filter_override', models.TextField()),
                ('password_last_change', models.DateTimeField(null=True)),
                ('login_tries', models.IntegerField(default='0')),
                ('login_last_try', models.DateTimeField(blank=True, null=True)),
                ('approved', models.IntegerField(default='1')),
                ('lang', models.CharField(blank=True, max_length=11)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('hidden_collections', models.TextField()),
                ('password_reset_hash', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('unique_hash', models.CharField(blank=True, max_length=50)),
                ('wp_authrequest', models.CharField(blank=True, max_length=50)),
                ('csrf_token', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('agent_type', models.IntegerField(choices=[(1, 'Person'), (2, 'Organization')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('filefield', models.FileField(max_length=255, upload_to='attachments/%Y/%m/')),
                ('filetype', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('value', domain.models.attribute.attribute_field.AttributeField()),
            ],
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AttributeReference',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('data_type', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=255)),
                ('term_type', models.CharField(blank=True, max_length=55)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=55, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('BOOL', 'BOOL (boolean)'),
                            ('DATE', 'DATE (date)'),
                            ('FKEY', 'FKEY (foreign key)'),
                            ('FLOAT', 'FLOAT (floating point)'),
                            ('INT', 'INT (integer)'),
                            ('JSON', 'JSON (data)'),
                            ('RREL', 'RREL (reverse relation)'),
                            ('STR', 'STR (string)'),
                        ],
                        max_length=15,
                    ),
                ),
                ('is_local', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('use_as_workset', models.BooleanField(default=False)),
                ('is_corpus', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollectionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['order', 'collection', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('object_id', models.CharField(db_index=True, max_length=55)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('getty_id', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('is_required', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=True)),
                ('override_label', models.CharField(blank=True, max_length=255)),
                ('override_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentTypeExtended',
            fields=[
                (
                    'contenttype_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='contenttypes.contenttype',
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_abstract', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('contenttypes.contenttype',),
            managers=[
                ('objects', django.contrib.contenttypes.models.ContentTypeManager()),
            ],
        ),
        migrations.CreateModel(
            name='CountryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alpha_3_code', models.CharField(max_length=3)),
                ('alpha_2_code', models.CharField(max_length=2)),
                ('num_code', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('label', models.CharField(max_length=55)),
                (
                    'kind',
                    models.CharField(
                        choices=[('W', 'Word enclosing element'), ('S', 'Stand-alone element')], max_length=1
                    ),
                ),
                (
                    'section',
                    models.CharField(
                        choices=[
                            ('annotation', 'Annotation'),
                            ('editorial', 'Editorial'),
                            ('formatting', 'Formatting'),
                            ('layout', 'Layout'),
                            ('marks', 'Marks'),
                            ('other', 'Other'),
                        ],
                        max_length=55,
                    ),
                ),
                ('description', models.TextField()),
                ('kb_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(max_length=55)),
                ('compound', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=55)),
                ('kind', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=False)),
                ('default', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElementSet',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityPhrase',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('object_id', models.UUIDField(db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Headword',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('word', models.CharField(max_length=55)),
                ('full_lemma', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('glottocode', models.CharField(max_length=25, unique=True)),
                ('iso6393', models.CharField(blank=True, default=None, max_length=25, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_dialect', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocaleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('administrative_region', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                (
                    'location_type',
                    models.IntegerField(choices=[(1, 'Address'), (2, 'Country'), (3, 'Geometry'), (4, 'Locale')]),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectAttribute',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'payload_type',
                    models.CharField(
                        choices=[
                            ('db_records', 'DB Records'),
                            ('field_choices', 'Field Choices'),
                            ('static_list', 'Static List'),
                        ],
                        max_length=15,
                    ),
                ),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('payload', models.JSONField()),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=55)),
                ('dam_id', models.IntegerField(db_index=True, null=True)),
                ('order', models.IntegerField(db_index=True)),
                ('canvas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('principal_id', models.PositiveIntegerField(db_index=True, null=True)),
                ('object_id', models.CharField(db_index=True, max_length=36)),
                ('is_default', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_remove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenceKey',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=55, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('BOOL', 'BOOL (boolean)'),
                            ('INT', 'INT (integer)'),
                            ('JSON', 'JSON (data)'),
                            ('STR', 'STR (string)'),
                        ],
                        max_length=15,
                    ),
                ),
                ('group', models.CharField(max_length=55)),
                ('default', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'zotero_library_id',
                    models.IntegerField(
                        help_text='Group ID for Zotero library to use for this project.',
                        null=True,
                        verbose_name='Zotero library ID',
                    ),
                ),
                (
                    'zotero_api_key',
                    models.CharField(
                        blank=True,
                        help_text="Zotero API key granting access to project's library.",
                        max_length=255,
                        verbose_name='Zotero API key',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PublicRegister',
            fields=[
                ('object_id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
                ('parent_id', models.CharField(db_index=True, max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='RecordGroup',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55)),
                ('parent_id', models.CharField(db_index=True, max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('source_object_id', models.CharField(db_index=True, max_length=36)),
                ('target_object_id', models.CharField(db_index=True, max_length=36)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('is_directed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RightsPolicy',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'rights_status',
                    models.IntegerField(
                        choices=[
                            (1, 'Copyrighted'),
                            (2, 'Orphaned'),
                            (3, 'Owned'),
                            (4, 'Public Domain'),
                            (5, 'Unknown'),
                        ],
                        default=5,
                    ),
                ),
                ('rights', models.TextField(blank=True)),
                ('rights_notice', models.JSONField(null=True)),
                ('licence', models.TextField(blank=True, null=True)),
                ('rights_holder', models.CharField(blank=True, max_length=255)),
                ('notice_display', models.BooleanField(default=False)),
                ('public_display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('shareable', models.BooleanField(default=False)),
                ('search', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('parameters', models.JSONField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScopeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=55, unique=True)),
                ('description', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                (
                    'tag_type',
                    models.CharField(choices=[('WF', 'Workflow'), ('C', 'Control'), ('T', 'Ticket')], max_length=2),
                ),
                ('tag', models.CharField(blank=True, max_length=55)),
                ('tag_group', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(default='')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Task Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('subject', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'creation_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('raw_token', models.CharField(max_length=255)),
                ('clean_token', models.CharField(max_length=55)),
                ('order', models.IntegerField(db_index=True)),
                ('flags', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('transcription', models.TextField(blank=True)),
                ('author', models.CharField(default=app.context.get_current_username, max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('count_ignore', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wordform',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                ('normalized_form', models.CharField(max_length=55)),
                ('pos', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('event', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZoteroCollection',
            fields=[
                ('creation_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                (
                    'modification_timestamp',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
                ),
                (
                    'id',
                    models.CharField(
                        help_text='Zotero ID of the collection.', max_length=25, primary_key=True, serialize=False
                    ),
                ),
                ('label', models.CharField(help_text='Label for the collection.', max_length=255)),
                (
                    'has_biblio_sources',
                    models.BooleanField(
                        default=False,
                        help_text='Indicates if entries in this collection should be included as potential sources for records.',
                        verbose_name='Contains sources?',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'agent_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='domain.agent',
                    ),
                ),
                ('short_name', models.CharField(max_length=55)),
            ],
            bases=('domain.agent',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'agent_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='domain.agent',
                    ),
                ),
            ],
            bases=('domain.agent',),
        ),
    ]
