# Generated by Django 5.0.4 on 2024-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0002_casts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(
                choices=[('public', 'public'), ('project', 'project')], default='project', max_length=100
            ),
        ),
    ]
