# Generated by Django 5.1.4 on 2025-02-21 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
