# Generated by Django 5.1.4 on 2025-03-07 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('domain', '0003_alter_worklog_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rs_collection',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rs_collection_resource',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rs_resource',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rs_resource_data',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rs_resource_type_field',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rs_user',
            options={'base_manager_name': 'objects', 'managed': False},
        ),
    ]
