export const columnMap = {
  name: {
    label: "Name",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: true,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
  },
  locationType: {
    label: "Location Type",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
    key: "locationType",
  },
  locationDetail: {
    label: "Location Type",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: true,
    key: "locationDetail",
  },
  attestationCount: {
    label: "Attestations",
    align: "center",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap text-center",
    isDefaultVisible: true,
    key: "attestationCount",
  },
  creationUser: {
    label: "Created by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    key: "fullName",
  },
  creationTimestamp: {
    label: "Created on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    key: "timestamp",
  },
  modificationUser: {
    label: "Modified by",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: null,
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    key: "fullName",
  },
  modificationTimestamp: {
    label: "Modified on",
    align: "left",
    sortable: true,
    sortOrder: "ad",
    isSortDefault: false,
    classes: "text-no-wrap",
    headerClasses: "text-no-wrap",
    isDefaultVisible: false,
    key: "timestamp",
  },
};
