# ; -*- mode: makefile ;-*-
# vi: set ft=make :
NODE_MODULES := $(UI)/node_modules
PROXY_PORT := 8000

ui.help:
	@echo "  ui.lint                  invoke eslint over the ui code"
	@echo "  ui.open                  view the ui in your browser"
	@echo "  ui.shell                 shell into the ui container"
	@echo "  ui.sync                  install the ui dependencies and rebuild the service"
	@echo "  ui.test                  run the ui test suite"
	@echo "  ui.test.debug            run the ui test suite and halt on breakpoints"
	@echo "  ui.test.watch            re-run the test suite on code changes"
	@echo ""
.PHONY: ui.help

ui.lint:
	docker compose run -T --rm \
		$(NAMESPACE).ui \
		yarn lint
.PHONY: ui.lint

ui.open:
	open http://localhost:$(PROXY_PORT)/db
.PHONY: ui.open

ui.shell:
	docker compose run --rm \
		$(NAMESPACE).ui \
		bash
.PHONY: ui.shell

ui.sync: _ui.install _ui.build
.PHONY: ui.sync

ui.test:
	yarn --cwd $(UI) test:unit
.PHONY: ui.test

ui.test.debug:
	yarn --cwd $(UI) test:unit:debug
.PHONY: ui.test.debug

ui.test.watch:
	yarn --cwd $(UI) test:unit:ui
.PHONY: ui.test.watch

### Private (non-interface) targets.
_ui.build:
	docker compose up -d --no-deps --build $(NAMESPACE).ui
.PHONY: _ui.build

_ui.init: _ui.install _ui.build
.PHONY: _ui.init

_ui.install:
	yarn --cwd $(UI) install
.PHONY: _ui.install
