# ; -*- mode: makefile ;-*-
# vi: set ft=make :
RESOLVER := /etc/resolver/localhost
TENANTS = dalme pharmacopeias

web.help:
	@echo "  web.collectstatic      bundle static files for all apps and tenants"
	@echo "  web.manage             call django management commands"
	@echo "  web.open               view the site in your browser"
	@echo "  web.python             shell into python on the web container"
	@echo "  web.shell              shell into the web container"
	@echo "  web.sync               install the web requirements and rebuild the service"
	@echo "  web.test               run the web test suite in full"
	@echo "  web.test.i             run only the web integration tests"
	@echo "  web.test.p             run only the web property tests"
	@echo "  web.test.u             run only the web unit tests"
	@echo "  web.test.watch         re-run the test suite on code changes"
	@echo ""
.PHONY: web.help

web.collectstatic:
	docker compose exec \
		$(NAMESPACE).web \
		python manage.py collectstatic_tenants
.PHONY: web.collectstatic

web.manage:
ifndef args
	$(error Call management commands with args. \
		Usage: make web.manage args='collectstatic --no-input')
else
	docker compose exec \
		$(NAMESPACE).web \
		python manage.py $(args)
endif
.PHONY: web.manage

web.migrate_data:
	docker compose exec \
		-e DATA_MIGRATION=1 \
		$(NAMESPACE).web \
		python manage.py migrate_data
.PHONY: web.manage

web.open:
	open http://dalme.localhost:8000/
.PHONY: web.open

web.python:
	docker compose exec \
		$(NAMESPACE).web \
		python manage.py shell_plus --print-sql
.PHONY: web.python

web.shell:
	docker compose exec \
		$(NAMESPACE).web \
		bash
.PHONY: web.shell

web.notebook:
	docker compose exec \
		$(NAMESPACE).web \
		python manage.py shell_plus --notebook
.PHONY: web.notebook

web.sync: _web.install _web.build
.PHONY: web.sync

web.test:
	docker compose run --rm \
		-e DEBUG='' \
		$(NAMESPACE).web \
		pytest -s \
		--cov=. \
		--cov-report=term-missing \
		--hypothesis-show-statistics \
		$(args)
.PHONY: web.test

web.test.i:
	docker compose run --rm \
		$(NAMESPACE).web \
		pytest -svv \
		-m 'integration' \
		--cov=. \
		--cov-report=term-missing \
		$(args)
.PHONY: web.test.i

web.test.p:
	docker compose run --rm \
		$(NAMESPACE).web \
		pytest -svv \
		-m 'property' \
		--cov=. \
		--cov-report=term-missing \
		--hypothesis-show-statistics \
		$(args)
.PHONY: web.test.p

web.test.u:
	docker compose run --rm \
		$(NAMESPACE).web \
		pytest -svv \
		-m 'unit' \
		--cov=. \
		--cov-report=term-missing \
		$(args)
.PHONY: web.test.u

web.test.watch:
	docker compose run --rm \
		$(NAMESPACE).web \
		ptw . $(args)
.PHONY: web.test.watch

### Private (non-interface) targets.
_web.build:
	 docker compose up -d --no-deps --build $(NAMESPACE).web
.PHONY: _web.build

_web.dns:
	sudo mkdir -p /etc/resolver
	[ -L $(RESOLVER) ] || sudo ln -s $(CONFIG)/localhost $(RESOLVER)
.PHONY: _web.dns

_web.init: _web.install _web.dns
.PHONY: _web.init

_web.install:
	$(VENV_BIN)/python3 -m \
		pip install -r $(ROOT)/requirements-dev.txt
.PHONY: _web.install
