# Generated by Django 5.0.3 on 2024-04-08 20:30

import wagtail.fields

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('public', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of the role.', max_length=255)),
                (
                    'parent',
                    models.ForeignKey(
                        help_text='Parent role, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='publicteam.teamrole',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name as it should appear on the front end.', max_length=255)),
                ('title', models.CharField(help_text='Professional title(s).', max_length=255)),
                ('affiliation', models.CharField(help_text='Institutional affiliation.', max_length=255)),
                ('biography', wagtail.fields.RichTextField(help_text='Short biographical sketch.')),
                ('url', models.URLField(blank=True, help_text='Link to a website or online profile.')),
                (
                    'photo',
                    models.ForeignKey(
                        help_text='Profile image or avatar.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='public.baseimage',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        help_text='Associated user record, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='team_member_record',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('roles', models.ManyToManyField(help_text='Project role(s).', to='publicteam.teamrole')),
            ],
        ),
    ]
