# Generated by Django 5.0.3 on 2024-04-30 22:04

import wagtail.fields
import wagtail.users.models

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of the role.', max_length=255)),
                ('description', models.TextField(help_text='Description of the role.')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent role, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='publicteam.teamrole',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name as it should appear on the front end.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Professional title(s).', max_length=255)),
                ('affiliation', models.CharField(blank=True, help_text='Institutional affiliation.', max_length=255)),
                ('biography', wagtail.fields.RichTextField(blank=True, help_text='Short biographical sketch.')),
                (
                    'url',
                    models.URLField(
                        blank=True, help_text='Link to a website or online profile.', verbose_name='Website'
                    ),
                ),
                (
                    'photo',
                    models.ImageField(
                        blank=True,
                        help_text='Profile image or avatar.',
                        null=True,
                        upload_to=wagtail.users.models.upload_avatar_to,
                        verbose_name='profile picture',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Associated user record, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='team_member_record',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('roles', models.ManyToManyField(blank=True, help_text='Project role(s).', to='publicteam.teamrole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('name', 'title'), name='unique_name_title'),
        ),
    ]
