# Generated by Django 4.2.2 on 2024-02-28 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityphrase',
            old_name='transcription_id',
            new_name='transcription',
        ),
    ]
