# Generated by Django 4.2.2 on 2023-12-11 09:51
from django.db import migrations


def change_user_type(apps, schema_editor):
    """Update the auth.User content type."""
    ContentType = apps.get_model('contenttypes', 'ContentType')  # noqa: N806
    ct = ContentType.objects.filter(app_label='auth', model='user').first()
    if ct:
        ct.app_label = 'ida'
        ct.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(change_user_type),
    ]
