# Generated by Django 4.2.2 on 2024-02-28 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0002_rename_transcription_id_entityphrase_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headword',
            old_name='concept_id',
            new_name='concept',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='object_phrase_id',
            new_name='object_phrase',
        ),
        migrations.RenameField(
            model_name='token',
            old_name='wordform_id',
            new_name='wordform',
        ),
        migrations.RenameField(
            model_name='wordform',
            old_name='headword_id',
            new_name='headword',
        ),
    ]
