# Generated by Django 4.2.2 on 2023-12-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0002_auto_20231211_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
