# Generated by Django 4.2.2 on 2024-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0003_rename_concept_id_headword_concept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='canvas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
