# Generated by Django 4.2.2 on 2023-12-13 14:09
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ida.models.user


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0003_alter_user_options_alter_user_id_alter_user_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Profile',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        ('full_name', models.CharField(blank=True, max_length=50)),
                        ('preferences', models.JSONField(default=ida.models.user.get_default_preferences)),
                        (
                            'user',
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='profile',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
