# Generated by Django 4.2.2 on 2023-12-13 15:04
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ida', '0004_profile'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='GroupProperties',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                            ),
                        ),
                        (
                            'group_type',
                            models.IntegerField(
                                choices=[(1, 'Admin'), (2, 'DAM'), (3, 'Team'), (4, 'Knowledge Base'), (5, 'Website')]
                            ),
                        ),
                        ('description', models.CharField(max_length=255)),
                        (
                            'group',
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='auth.group'
                            ),
                        ),
                    ],
                ),
            ],
            database_operations=[],
        ),
    ]
