# Generated by Django 4.2.2 on 2024-03-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0004_alter_page_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightspolicy',
            name='licence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
