# Generated by Django 4.2.2 on 2023-12-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0005_groupproperties'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='groupproperties',
                    name='tenant',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ida.tenant'),
                ),
            ],
            database_operations=[],
        ),
    ]
