# Generated by Django 4.2.2 on 2024-03-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0006_alter_ticket_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
