# Generated by Django 4.2.2 on 2023-12-13 16:20
import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0020_remove_organization_agent_ptr_and_more'),
        ('ida', '0006_groupproperties_tenant'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Agent',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('agent_type', models.IntegerField(choices=[(1, 'Person'), (2, 'Organization')])),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Person',
                    fields=[
                        (
                            'agent_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.agent',
                            ),
                        ),
                        (
                            'user',
                            models.OneToOneField(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='person_record',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.agent',),
                ),
                migrations.CreateModel(
                    name='Organization',
                    fields=[
                        (
                            'agent_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.agent',
                            ),
                        ),
                        ('short_name', models.CharField(max_length=55)),
                        (
                            'location',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.PROTECT, to='dalme_app.location'
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.agent',),
                ),
            ],
            database_operations=[],
        ),
    ]
