# Generated by Django 4.2.2 on 2024-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0007_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
