# Generated by Django 4.2.2 on 2024-03-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0008_alter_attributetype_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ida.attributetype'
            ),
        ),
    ]
