# Generated by Django 4.2.2 on 2023-12-13 17:49
import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ida.models.templates


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0010_wordform'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Transcription',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('transcription', models.TextField(blank=True)),
                        ('author', models.CharField(default=ida.models.templates.get_current_username, max_length=255)),
                        ('version', models.IntegerField(default=1)),
                        ('count_ignore', models.BooleanField(default=False)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
