# Generated by Django 4.2.2 on 2023-12-13 18:06
import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0026_delete_ticket'),
        ('ida', '0012_token'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Ticket',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('subject', models.CharField(max_length=140)),
                        ('description', models.TextField(blank=True)),
                        ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                        ('url', models.CharField(blank=True, max_length=255)),
                        ('closing_date', models.DateTimeField(blank=True, null=True)),
                        (
                            'assigned_to',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='ticket_assigned_to',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'closing_user',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'files',
                            models.ManyToManyField(blank=True, related_name='tickets', to='dalme_app.attachment'),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['status', 'creation_timestamp'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
