# Generated by Django 4.2.2 on 2023-12-13 18:20
import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dalme_app', '0028_delete_rightspolicy'),
        ('ida', '0014_scopetype_scope'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='RightsPolicy',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('name', models.CharField(max_length=100)),
                        (
                            'rights_status',
                            models.IntegerField(
                                choices=[
                                    (1, 'Copyrighted'),
                                    (2, 'Orphaned'),
                                    (3, 'Owned'),
                                    (4, 'Public Domain'),
                                    (5, 'Unknown'),
                                ],
                                default=5,
                            ),
                        ),
                        ('rights', models.TextField(blank=True)),
                        ('rights_notice', models.JSONField(null=True)),
                        ('licence', models.TextField(blank=True)),
                        ('rights_holder', models.CharField(blank=True, max_length=255)),
                        ('notice_display', models.BooleanField(default=False)),
                        ('public_display', models.BooleanField(default=True)),
                        (
                            'attachments',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to='dalme_app.attachment',
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
