# Generated by Django 4.2.2 on 2023-12-14 10:52
import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ida', '0018_place'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PublicRegister',
                    fields=[
                        ('object_id', models.UUIDField(db_index=True, primary_key=True, serialize=False)),
                        ('created', models.DateTimeField(auto_now_add=True, null=True)),
                        (
                            'content_type',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'
                            ),
                        ),
                        (
                            'creator',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['created'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
