# Generated by Django 4.2.2 on 2023-12-15 23:29

import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ida', '0019_publicregister'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Permission',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('principal_id', models.PositiveIntegerField(db_index=True, null=True)),
                        ('object_id', models.CharField(db_index=True, max_length=36)),
                        ('is_default', models.BooleanField(default=False)),
                        ('can_view', models.BooleanField(default=False)),
                        ('can_edit', models.BooleanField(default=False)),
                        ('can_delete', models.BooleanField(default=False)),
                        ('can_add', models.BooleanField(default=False)),
                        ('can_remove', models.BooleanField(default=False)),
                        (
                            'content_type',
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='cperm_objects',
                                to='contenttypes.contenttype',
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'principal_type',
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='cperm_principals',
                                to='contenttypes.contenttype',
                            ),
                        ),
                    ],
                    options={
                        'unique_together': {('content_type', 'object_id', 'principal_type', 'principal_id')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
