# Generated by Django 4.2.2 on 2023-12-16 12:44

import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0022_optionslist'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Location',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        (
                            'location_type',
                            models.IntegerField(
                                choices=[(1, 'Address'), (2, 'Country'), (3, 'Geometry'), (4, 'Locale')]
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.AlterField(
                    model_name='organization',
                    name='location',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ida.location'),
                ),
                migrations.AlterField(
                    model_name='place',
                    name='location',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.location'),
                ),
            ],
            database_operations=[],
        ),
    ]
