# Generated by Django 4.2.2 on 2023-12-16 13:10

import django_currentuser.middleware

import django.contrib.contenttypes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dalme_app', '0040_remove_contenttypeextended_attribute_types_and_more'),
        ('ida', '0025_object_objectattribute'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ContentAttributes',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('is_required', models.BooleanField(default=False)),
                        ('is_unique', models.BooleanField(default=True)),
                        ('override_label', models.CharField(blank=True, max_length=255)),
                        ('override_description', models.TextField(blank=True)),
                        (
                            'attribute_type',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='contenttypes',
                                to='dalme_app.attributetype',
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name='ContentTypeExtended',
                    fields=[
                        (
                            'contenttype_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='contenttypes.contenttype',
                            ),
                        ),
                        ('name', models.CharField(max_length=255, unique=True)),
                        ('description', models.TextField()),
                        ('is_abstract', models.BooleanField(default=True)),
                        ('can_view', models.BooleanField(default=True)),
                        ('can_edit', models.BooleanField(default=False)),
                        ('can_delete', models.BooleanField(default=False)),
                        ('can_add', models.BooleanField(default=False)),
                        ('can_remove', models.BooleanField(default=False)),
                        (
                            'attribute_types',
                            models.ManyToManyField(through='ida.ContentAttributes', to='dalme_app.attributetype'),
                        ),
                        (
                            'parent',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.contenttypeextended'
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['id'],
                    },
                    bases=('contenttypes.contenttype',),
                    managers=[
                        ('objects', django.contrib.contenttypes.models.ContentTypeManager()),
                    ],
                ),
                migrations.AddField(
                    model_name='contentattributes',
                    name='content_type',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attributes_list',
                        to='ida.contenttypeextended',
                    ),
                ),
                migrations.AddField(
                    model_name='contentattributes',
                    name='creation_user',
                    field=models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_creation',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name='contentattributes',
                    name='modification_user',
                    field=models.ForeignKey(
                        default=django_currentuser.middleware.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='%(app_label)s_%(class)s_modification',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddField(
                    model_name='contentattributes',
                    name='override_options',
                    field=models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.optionslist'
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name='contentattributes',
                    unique_together={('content_type', 'attribute_type')},
                ),
            ],
            database_operations=[],
        ),
    ]
