# Generated by Django 4.2.2 on 2023-12-16 13:28
import uuid

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0026_contentattributes_contenttypeextended_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CountryReference',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('name', models.CharField(max_length=255, unique=True)),
                        ('alpha_3_code', models.CharField(max_length=3)),
                        ('alpha_2_code', models.CharField(max_length=2)),
                        ('num_code', models.IntegerField()),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='LanguageReference',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('glottocode', models.CharField(max_length=25, unique=True)),
                        ('iso6393', models.CharField(blank=True, default=None, max_length=25, null=True, unique=True)),
                        ('name', models.CharField(max_length=255)),
                        ('is_dialect', models.BooleanField(default=False)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'parent',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.languagereference'
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='AttributeReference',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('short_name', models.CharField(max_length=55)),
                        ('description', models.TextField()),
                        ('data_type', models.CharField(max_length=15)),
                        ('source', models.CharField(max_length=255)),
                        ('term_type', models.CharField(blank=True, max_length=55)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='LocaleReference',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('name', models.CharField(max_length=255)),
                        ('administrative_region', models.CharField(max_length=255)),
                        ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                        ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                        (
                            'country',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.countryreference'
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['country', 'name'],
                        'unique_together': {('name', 'administrative_region')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
