# Generated by Django 4.2.2 on 2023-12-18 10:53

import django_currentuser.middleware

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0027_countryreference_languagereference_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AttributeType',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        ('name', models.CharField(max_length=55, unique=True)),
                        ('label', models.CharField(max_length=255)),
                        ('description', models.TextField()),
                        (
                            'data_type',
                            models.CharField(
                                choices=[
                                    ('BOOL', 'BOOL (boolean)'),
                                    ('DATE', 'DATE (date)'),
                                    ('DEC', 'DEC (decimal)'),
                                    ('FKEY', 'FKEY (foreign key)'),
                                    ('INT', 'INT (integer)'),
                                    ('JSON', 'JSON (data)'),
                                    ('RREL', 'RREL (reverse relation)'),
                                    ('STR', 'STR (string)'),
                                    ('TXT', 'TXT (text)'),
                                ],
                                max_length=15,
                            ),
                        ),
                        ('is_local', models.BooleanField(default=False)),
                        ('source', models.CharField(blank=True, max_length=255)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'options',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.optionslist'
                            ),
                        ),
                        (
                            'same_as',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.SET_NULL, to='ida.attributetype'
                            ),
                        ),
                    ],
                    options={
                        'ordering': ['id'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='contentattributes',
                    name='attribute_type',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='contenttypes', to='ida.attributetype'
                    ),
                ),
                migrations.AlterField(
                    model_name='contenttypeextended',
                    name='attribute_types',
                    field=models.ManyToManyField(through='ida.ContentAttributes', to='ida.attributetype'),
                ),
            ],
            database_operations=[],
        ),
    ]
