# Generated by Django 4.2.2 on 2023-12-18 11:12

import uuid

import django_currentuser.middleware
import wagtail.search.index

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ida', '0028_attributetype_alter_contentattributes_attribute_type_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Folio',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'page',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ida.page'
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='RecordGroup',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('short_name', models.CharField(max_length=55)),
                        ('parent_id', models.CharField(db_index=True, max_length=36, null=True)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'owner',
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_related',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'parent_type',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Record',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('name', models.CharField(max_length=255)),
                        ('short_name', models.CharField(max_length=55)),
                        ('parent_id', models.CharField(db_index=True, max_length=36, null=True)),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'owner',
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_related',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        ('pages', models.ManyToManyField(db_index=True, through='ida.Folio', to='ida.page')),
                        (
                            'parent_type',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=(wagtail.search.index.Indexed, models.Model),
                ),
                migrations.AddField(
                    model_name='folio',
                    name='record',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='folios', to='ida.record'
                    ),
                ),
                migrations.AddField(
                    model_name='folio',
                    name='transcription',
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='folios',
                        to='ida.transcription',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
