# Generated by Django 4.2.2 on 2023-12-18 16:17

import uuid

import django_currentuser.middleware

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ida', '0029_folio_recordgroup_record_folio_record_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Attribute',
                    fields=[
                        ('creation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                        ('modification_timestamp', models.DateTimeField(auto_now=True, null=True)),
                        (
                            'id',
                            models.UUIDField(
                                db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                            ),
                        ),
                        ('object_id', models.CharField(db_index=True, max_length=36)),
                        (
                            'attribute_type',
                            models.ForeignKey(
                                db_column='attribute_type',
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='attributes',
                                to='ida.attributetype',
                            ),
                        ),
                        (
                            'content_type',
                            models.ForeignKey(
                                null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'
                            ),
                        ),
                        (
                            'creation_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_creation',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            'modification_user',
                            models.ForeignKey(
                                default=django_currentuser.middleware.get_current_user,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='%(app_label)s_%(class)s_modification',
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='AttributeValueBool',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.BooleanField()),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueDate',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        (
                            'day',
                            models.PositiveSmallIntegerField(
                                null=True,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(31),
                                ],
                            ),
                        ),
                        (
                            'month',
                            models.PositiveSmallIntegerField(
                                null=True,
                                validators=[
                                    django.core.validators.MinValueValidator(1),
                                    django.core.validators.MaxValueValidator(12),
                                ],
                            ),
                        ),
                        ('year', models.IntegerField(null=True)),
                        ('date', models.DateField(null=True)),
                        ('text', models.CharField(blank=True, max_length=255)),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueDec',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueInt',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.IntegerField()),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueJson',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.JSONField()),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueStr',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.CharField(max_length=255)),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueTxt',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('value', models.TextField()),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
                migrations.CreateModel(
                    name='AttributeValueFkey',
                    fields=[
                        (
                            'attribute_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='ida.attribute',
                            ),
                        ),
                        ('target_id', models.CharField(db_index=True, max_length=36)),
                        (
                            'target_content_type',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='fk_attributes',
                                to='contenttypes.contenttype',
                            ),
                        ),
                    ],
                    options={
                        'abstract': False,
                    },
                    bases=('ida.attribute',),
                ),
            ],
            database_operations=[],
        ),
    ]
