# Generated by Django 4.2.2 on 2024-01-15 16:54
import django.db.models.deletion
from django.db import migrations, models


def scope_group_properties(apps, schema_editor):
    """Scope Group Properties to tenants."""
    Group = apps.get_model('auth', 'Group')  # noqa: N806
    GroupProperties = apps.get_model('ida', 'GroupProperties')  # noqa: N806
    Tenant = apps.get_model('ida', 'Tenant')  # noqa: N806

    # Fix a missing Group.properties field, not sure how that has occurred.
    group = Group.objects.get(pk=37)
    GroupProperties.objects.create(
        tenant=None,
        group=group,
        group_type=1,
        description='Group housing site content moderators',
    )

    unscoped = {'DAM Editors', 'DAM Users', 'Developers' 'Super Administrators'}
    dalme = Tenant.objects.get(name='DALME')
    for obj in GroupProperties.objects.all():
        if obj.group.name not in unscoped:
            obj.tenant = dalme
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0034_auto_20240108_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproperties',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ida.tenant'),
        ),
        migrations.RunPython(scope_group_properties),
    ]
