# Generated by Django 4.2.2 on 2024-01-15 16:54
import django.db.models.deletion
from django.db import migrations, models


def scope_group_properties(apps, schema_editor):
    """Scope Group Properties to tenants."""
    GroupProperties = apps.get_model('ida', 'GroupProperties')  # noqa: N806
    Tenant = apps.get_model('ida', 'Tenant')  # noqa: N806

    unscoped = {'DAM Editors', 'DAM Users', 'Developers' 'Super Administrators'}
    dalme = Tenant.objects.get(name='DALME')
    for obj in GroupProperties.objects.all():
        if obj.group.name not in unscoped:
            obj.tenant = dalme
            obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0034_auto_20240108_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproperties',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ida.tenant'),
        ),
        migrations.RunPython(scope_group_properties),
    ]
