# Generated by Django 4.2.2 on 2024-01-17 13:37
from django.db import migrations


def scope_tenant_members(apps, schema_editor):
    """Register exisiting users with DALME tenant."""
    Tenant = apps.get_model('ida', 'Tenant')  # noqa: N806
    User = apps.get_model('ida', 'User')  # noqa: N806

    dalme = Tenant.objects.get(name='DALME')
    dalme.members.add(*User.objects.exclude(tenant=dalme))


class Migration(migrations.Migration):
    dependencies = [
        ('ida', '0035_groupproperties_tenant'),
    ]

    operations = [
        migrations.RunPython(scope_tenant_members),
    ]
