# Generated by Django 4.2.2 on 2024-02-15 13:45

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ida', '0037_auto_20240117_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyGroup',
            fields=[],
            options={
                'verbose_name': 'Group',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'OAuth Application'},
        ),
    ]
