# Generated by Django 5.0.4 on 2024-12-20 21:56

import wagtail.fields

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('webimages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of the role.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of the role.')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent role, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='webteam.teamrole',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name as it should appear on the front end.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Professional title(s).', max_length=255)),
                ('affiliation', models.CharField(blank=True, help_text='Institutional affiliation.', max_length=255)),
                ('biography', wagtail.fields.RichTextField(blank=True, help_text='Short biographical sketch.')),
                (
                    'url',
                    models.URLField(
                        blank=True, help_text='Link to a website or online profile.', verbose_name='Website'
                    ),
                ),
                (
                    'photo',
                    models.ForeignKey(
                        blank=True,
                        help_text='Profile image or avatar.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to='webimages.baseimage',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Associated user record, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='team_member_record',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('roles', models.ManyToManyField(blank=True, help_text='Project role(s).', to='webteam.teamrole')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user', nulls_distinct=True),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(
                models.F('name'), django.db.models.functions.text.Lower('title'), name='unique_name_lower_title'
            ),
        ),
    ]
