# Generated by Django 5.1.4 on 2025-01-02 19:21

import wagtail.fields

import django.core.files.storage
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import domain.models.avatar


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Name of the role.', max_length=255, unique=True)),
                ('description', models.TextField(help_text='Description of the role.')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        help_text='Parent role, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='webteam.teamrole',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'avatar',
                    domain.models.avatar.AvatarField(
                        blank=True,
                        help_text='Profile image or avatar.',
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=domain.models.avatar.avatar_file_path,
                    ),
                ),
                ('name', models.CharField(help_text='Name as it should appear on the front end.', max_length=255)),
                ('title', models.CharField(blank=True, help_text='Professional title(s).', max_length=255)),
                ('affiliation', models.CharField(blank=True, help_text='Institutional affiliation.', max_length=255)),
                ('biography', wagtail.fields.RichTextField(blank=True, help_text='Short biographical sketch.')),
                (
                    'url',
                    models.URLField(
                        blank=True, help_text='Link to a website or online profile.', verbose_name='Website'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        help_text='Associated user record, if any.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='team_member_record',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('roles', models.ManyToManyField(blank=True, help_text='Project role(s).', to='webteam.teamrole')),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('user',), name='unique_user', nulls_distinct=True),
                    models.UniqueConstraint(
                        models.F('name'), django.db.models.functions.text.Lower('title'), name='unique_name_lower_title'
                    ),
                ],
            },
        ),
    ]
