# Generated by Django 5.1.4 on 2025-02-24 17:07

from django.db import migrations

import domain.models.avatar


class Migration(migrations.Migration):
    dependencies = [
        ('webteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='avatar',
            field=domain.models.avatar.AvatarField(
                blank=True,
                help_text='Profile image or avatar.',
                null=True,
                upload_to=domain.models.avatar.avatar_file_path,
            ),
        ),
    ]
