# Generated by Django 5.1.4 on 2025-04-05 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webteam', '0002_alter_teammember_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamrole',
            options={'ordering': ['-parent__role', '-role']},
        ),
    ]
